/*
WB Supplier Stats

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	// номер заказа
	Number int64 `json:"number"`
	// дата заказа
	Date string `json:"date"`
	// дата время обновления информации в сервисе
	LastChangeDate string `json:"lastChangeDate"`
	// ваш артикул
	SupplierArticle string `json:"supplierArticle"`
	// размер
	TechSize string `json:"techSize"`
	// штрих-код
	Barcode string `json:"barcode"`
	// кол-во
	Quantity int32 `json:"quantity"`
	// цена до согласованной скидки/промо/спп
	TotalPrice float32 `json:"totalPrice"`
	// согласованный итоговый дисконт
	DiscountPercent float32 `json:"discountPercent"`
	// склад отгрузки
	WarehouseName string `json:"warehouseName"`
	// область
	Oblast string `json:"oblast"`
	// номер поставки
	IncomeID int64 `json:"incomeID"`
	// уникальный идентификатор позиции заказа
	Odid int64 `json:"odid"`
	// Код WB
	NmId int32 `json:"nmId"`
	// предмет
	Subject string `json:"subject"`
	// категория
	Category string `json:"category"`
	// бренд
	Brand string `json:"brand"`
	// признак отмены заказа (0 – отмены не было, 1 – отмена была
	IsCancel bool `json:"isCancel"`
	// дата отмены заказа
	CancelDt string `json:"cancel_dt"`
	GNumber string `json:"gNumber"`
}

// NewInlineResponse200 instantiates a new InlineResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200(number int64, date string, lastChangeDate string, supplierArticle string, techSize string, barcode string, quantity int32, totalPrice float32, discountPercent float32, warehouseName string, oblast string, incomeID int64, odid int64, nmId int32, subject string, category string, brand string, isCancel bool, cancelDt string, gNumber string) *InlineResponse200 {
	this := InlineResponse200{}
	this.Number = number
	this.Date = date
	this.LastChangeDate = lastChangeDate
	this.SupplierArticle = supplierArticle
	this.TechSize = techSize
	this.Barcode = barcode
	this.Quantity = quantity
	this.TotalPrice = totalPrice
	this.DiscountPercent = discountPercent
	this.WarehouseName = warehouseName
	this.Oblast = oblast
	this.IncomeID = incomeID
	this.Odid = odid
	this.NmId = nmId
	this.Subject = subject
	this.Category = category
	this.Brand = brand
	this.IsCancel = isCancel
	this.CancelDt = cancelDt
	this.GNumber = gNumber
	return &this
}

// NewInlineResponse200WithDefaults instantiates a new InlineResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200WithDefaults() *InlineResponse200 {
	this := InlineResponse200{}
	return &this
}

// GetNumber returns the Number field value
func (o *InlineResponse200) GetNumber() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetNumberOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *InlineResponse200) SetNumber(v int64) {
	o.Number = v
}

// GetDate returns the Date field value
func (o *InlineResponse200) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetDateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *InlineResponse200) SetDate(v string) {
	o.Date = v
}

// GetLastChangeDate returns the LastChangeDate field value
func (o *InlineResponse200) GetLastChangeDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastChangeDate
}

// GetLastChangeDateOk returns a tuple with the LastChangeDate field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetLastChangeDateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastChangeDate, true
}

// SetLastChangeDate sets field value
func (o *InlineResponse200) SetLastChangeDate(v string) {
	o.LastChangeDate = v
}

// GetSupplierArticle returns the SupplierArticle field value
func (o *InlineResponse200) GetSupplierArticle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SupplierArticle
}

// GetSupplierArticleOk returns a tuple with the SupplierArticle field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetSupplierArticleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SupplierArticle, true
}

// SetSupplierArticle sets field value
func (o *InlineResponse200) SetSupplierArticle(v string) {
	o.SupplierArticle = v
}

// GetTechSize returns the TechSize field value
func (o *InlineResponse200) GetTechSize() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TechSize
}

// GetTechSizeOk returns a tuple with the TechSize field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetTechSizeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TechSize, true
}

// SetTechSize sets field value
func (o *InlineResponse200) SetTechSize(v string) {
	o.TechSize = v
}

// GetBarcode returns the Barcode field value
func (o *InlineResponse200) GetBarcode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Barcode
}

// GetBarcodeOk returns a tuple with the Barcode field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetBarcodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Barcode, true
}

// SetBarcode sets field value
func (o *InlineResponse200) SetBarcode(v string) {
	o.Barcode = v
}

// GetQuantity returns the Quantity field value
func (o *InlineResponse200) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetQuantityOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *InlineResponse200) SetQuantity(v int32) {
	o.Quantity = v
}

// GetTotalPrice returns the TotalPrice field value
func (o *InlineResponse200) GetTotalPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalPrice
}

// GetTotalPriceOk returns a tuple with the TotalPrice field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetTotalPriceOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TotalPrice, true
}

// SetTotalPrice sets field value
func (o *InlineResponse200) SetTotalPrice(v float32) {
	o.TotalPrice = v
}

// GetDiscountPercent returns the DiscountPercent field value
func (o *InlineResponse200) GetDiscountPercent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DiscountPercent
}

// GetDiscountPercentOk returns a tuple with the DiscountPercent field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetDiscountPercentOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DiscountPercent, true
}

// SetDiscountPercent sets field value
func (o *InlineResponse200) SetDiscountPercent(v float32) {
	o.DiscountPercent = v
}

// GetWarehouseName returns the WarehouseName field value
func (o *InlineResponse200) GetWarehouseName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WarehouseName
}

// GetWarehouseNameOk returns a tuple with the WarehouseName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetWarehouseNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WarehouseName, true
}

// SetWarehouseName sets field value
func (o *InlineResponse200) SetWarehouseName(v string) {
	o.WarehouseName = v
}

// GetOblast returns the Oblast field value
func (o *InlineResponse200) GetOblast() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Oblast
}

// GetOblastOk returns a tuple with the Oblast field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetOblastOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Oblast, true
}

// SetOblast sets field value
func (o *InlineResponse200) SetOblast(v string) {
	o.Oblast = v
}

// GetIncomeID returns the IncomeID field value
func (o *InlineResponse200) GetIncomeID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.IncomeID
}

// GetIncomeIDOk returns a tuple with the IncomeID field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetIncomeIDOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IncomeID, true
}

// SetIncomeID sets field value
func (o *InlineResponse200) SetIncomeID(v int64) {
	o.IncomeID = v
}

// GetOdid returns the Odid field value
func (o *InlineResponse200) GetOdid() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Odid
}

// GetOdidOk returns a tuple with the Odid field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetOdidOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Odid, true
}

// SetOdid sets field value
func (o *InlineResponse200) SetOdid(v int64) {
	o.Odid = v
}

// GetNmId returns the NmId field value
func (o *InlineResponse200) GetNmId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NmId
}

// GetNmIdOk returns a tuple with the NmId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetNmIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NmId, true
}

// SetNmId sets field value
func (o *InlineResponse200) SetNmId(v int32) {
	o.NmId = v
}

// GetSubject returns the Subject field value
func (o *InlineResponse200) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetSubjectOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *InlineResponse200) SetSubject(v string) {
	o.Subject = v
}

// GetCategory returns the Category field value
func (o *InlineResponse200) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetCategoryOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *InlineResponse200) SetCategory(v string) {
	o.Category = v
}

// GetBrand returns the Brand field value
func (o *InlineResponse200) GetBrand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Brand
}

// GetBrandOk returns a tuple with the Brand field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetBrandOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Brand, true
}

// SetBrand sets field value
func (o *InlineResponse200) SetBrand(v string) {
	o.Brand = v
}

// GetIsCancel returns the IsCancel field value
func (o *InlineResponse200) GetIsCancel() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsCancel
}

// GetIsCancelOk returns a tuple with the IsCancel field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetIsCancelOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsCancel, true
}

// SetIsCancel sets field value
func (o *InlineResponse200) SetIsCancel(v bool) {
	o.IsCancel = v
}

// GetCancelDt returns the CancelDt field value
func (o *InlineResponse200) GetCancelDt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CancelDt
}

// GetCancelDtOk returns a tuple with the CancelDt field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetCancelDtOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CancelDt, true
}

// SetCancelDt sets field value
func (o *InlineResponse200) SetCancelDt(v string) {
	o.CancelDt = v
}

// GetGNumber returns the GNumber field value
func (o *InlineResponse200) GetGNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GNumber
}

// GetGNumberOk returns a tuple with the GNumber field value
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetGNumberOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.GNumber, true
}

// SetGNumber sets field value
func (o *InlineResponse200) SetGNumber(v string) {
	o.GNumber = v
}

func (o InlineResponse200) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["number"] = o.Number
	}
	if true {
		toSerialize["date"] = o.Date
	}
	if true {
		toSerialize["lastChangeDate"] = o.LastChangeDate
	}
	if true {
		toSerialize["supplierArticle"] = o.SupplierArticle
	}
	if true {
		toSerialize["techSize"] = o.TechSize
	}
	if true {
		toSerialize["barcode"] = o.Barcode
	}
	if true {
		toSerialize["quantity"] = o.Quantity
	}
	if true {
		toSerialize["totalPrice"] = o.TotalPrice
	}
	if true {
		toSerialize["discountPercent"] = o.DiscountPercent
	}
	if true {
		toSerialize["warehouseName"] = o.WarehouseName
	}
	if true {
		toSerialize["oblast"] = o.Oblast
	}
	if true {
		toSerialize["incomeID"] = o.IncomeID
	}
	if true {
		toSerialize["odid"] = o.Odid
	}
	if true {
		toSerialize["nmId"] = o.NmId
	}
	if true {
		toSerialize["subject"] = o.Subject
	}
	if true {
		toSerialize["category"] = o.Category
	}
	if true {
		toSerialize["brand"] = o.Brand
	}
	if true {
		toSerialize["isCancel"] = o.IsCancel
	}
	if true {
		toSerialize["cancel_dt"] = o.CancelDt
	}
	if true {
		toSerialize["gNumber"] = o.GNumber
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200 struct {
	value *InlineResponse200
	isSet bool
}

func (v NullableInlineResponse200) Get() *InlineResponse200 {
	return v.value
}

func (v *NullableInlineResponse200) Set(val *InlineResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200(val *InlineResponse200) *NullableInlineResponse200 {
	return &NullableInlineResponse200{value: val, isSet: true}
}

func (v NullableInlineResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


