/*
WB Supplier Stats

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse2005 struct for InlineResponse2005
type InlineResponse2005 struct {
	// Идентификатор отчёта
	RealizationreportId int32 `json:"realizationreport_id"`
	// Договор
	SuppliercontractCode *int32 `json:"suppliercontract_code,omitempty"`
	// Идентификатор записи
	RrdId float32 `json:"rrd_id"`
	// Идентификатор поставки
	GiId float32 `json:"gi_id"`
	// Наименование товара
	SubjectName string `json:"subject_name"`
	// SKU товара
	NmId float32 `json:"nm_id"`
	// Бренд товара
	BrandName string `json:"brand_name"`
	// Артикул поставщика
	SaName string `json:"sa_name"`
	// Размер
	TsName string `json:"ts_name"`
	// Баркод
	Barcode string `json:"barcode"`
	// Тип документа
	DocTypeName string `json:"doc_type_name"`
	// Количество
	Quantity float32 `json:"quantity"`
	// Розничная цена
	RetailPrice float32 `json:"retail_price"`
	// Сумма продаж (возвратов)
	RetailAmount float32 `json:"retail_amount"`
	// Согласованная скидка
	SalePercent float32 `json:"sale_percent"`
	// Процент комиссии
	CommissionPercent float32 `json:"commission_percent"`
	// Наименование склада
	OfficeName string `json:"office_name"`
	// Обоснование для оплаты (Тип операции?)
	SupplierOperName string `json:"supplier_oper_name"`
	// Дата заказа
	OrderDt string `json:"order_dt"`
	// Дата продажи
	SaleDt string `json:"sale_dt"`
	// Дата операции
	RrDt string `json:"rr_dt"`
	// Штрих код (короба?)
	ShkId int32 `json:"shk_id"`
	// Розничная цена с учётом согласованной скидки
	RetailPriceWithdiscRub float32 `json:"retail_price_withdisc_rub"`
	// Количество доставок
	DeliveryAmount float32 `json:"delivery_amount"`
	// Количество возвратов
	ReturnAmount float32 `json:"return_amount"`
	// Стоимость логистики
	DeliveryRub float32 `json:"delivery_rub"`
	// Тип коробов
	GiBoxTypeName string `json:"gi_box_type_name"`
	// Согласованный продуктовый дисконт
	ProductDiscountForReport float32 `json:"product_discount_for_report"`
	// Промокод
	SupplierPromo float32 `json:"supplier_promo"`
	// Идентификатор позиции заказа
	Rid int32 `json:"rid"`
	// Скидка постоянного покупателя
	PpvzSppPrc float32 `json:"ppvz_spp_prc"`
	// Базовый размер коэффициента вознаграждения вайлдберриз без НДС, %
	PpvzKvwPrcBase float32 `json:"ppvz_kvw_prc_base"`
	// Итоговый размер коэффициента вознаграждения вайлдберриз без НДС, %
	PpvzKvwPrc float32 `json:"ppvz_kvw_prc"`
	// Вознаграждение с продаж до вычета услуг поверенного, без НДС
	PpvzSalesCommission float32 `json:"ppvz_sales_commission"`
	// К перечислению продавцу за реализованный Товар
	PpvzForPay float32 `json:"ppvz_for_pay"`
	// Возмещение расходов услуг поверенного
	PpvzReward float32 `json:"ppvz_reward"`
	// Вознаграждение вайлдберриз, без НДС
	PpvzVw float32 `json:"ppvz_vw"`
	// НДС с вознаграждения вайлдберриз
	PpvzVwNds float32 `json:"ppvz_vw_nds"`
	// Идентификатор ПВЗ?
	PpvzOfficeId int32 `json:"ppvz_office_id"`
	// Наименование ПВЗ? (в случае если ppvz_office_id = 0)
	PpvzOfficeName *string `json:"ppvz_office_name,omitempty"`
	// Идентификатор владельца ПВЗ?
	PpvzSupplierId int32 `json:"ppvz_supplier_id"`
	// Наименование владельца ПВЗ
	PpvzSupplierName *string `json:"ppvz_supplier_name,omitempty"`
	// ИНН владельца ПВЗ
	PpvzSupplierInn *string `json:"ppvz_supplier_inn,omitempty"`
}

// NewInlineResponse2005 instantiates a new InlineResponse2005 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2005(realizationreportId int32, rrdId float32, giId float32, subjectName string, nmId float32, brandName string, saName string, tsName string, barcode string, docTypeName string, quantity float32, retailPrice float32, retailAmount float32, salePercent float32, commissionPercent float32, officeName string, supplierOperName string, orderDt string, saleDt string, rrDt string, shkId int32, retailPriceWithdiscRub float32, deliveryAmount float32, returnAmount float32, deliveryRub float32, giBoxTypeName string, productDiscountForReport float32, supplierPromo float32, rid int32, ppvzSppPrc float32, ppvzKvwPrcBase float32, ppvzKvwPrc float32, ppvzSalesCommission float32, ppvzForPay float32, ppvzReward float32, ppvzVw float32, ppvzVwNds float32, ppvzOfficeId int32, ppvzSupplierId int32) *InlineResponse2005 {
	this := InlineResponse2005{}
	this.RealizationreportId = realizationreportId
	this.RrdId = rrdId
	this.GiId = giId
	this.SubjectName = subjectName
	this.NmId = nmId
	this.BrandName = brandName
	this.SaName = saName
	this.TsName = tsName
	this.Barcode = barcode
	this.DocTypeName = docTypeName
	this.Quantity = quantity
	this.RetailPrice = retailPrice
	this.RetailAmount = retailAmount
	this.SalePercent = salePercent
	this.CommissionPercent = commissionPercent
	this.OfficeName = officeName
	this.SupplierOperName = supplierOperName
	this.OrderDt = orderDt
	this.SaleDt = saleDt
	this.RrDt = rrDt
	this.ShkId = shkId
	this.RetailPriceWithdiscRub = retailPriceWithdiscRub
	this.DeliveryAmount = deliveryAmount
	this.ReturnAmount = returnAmount
	this.DeliveryRub = deliveryRub
	this.GiBoxTypeName = giBoxTypeName
	this.ProductDiscountForReport = productDiscountForReport
	this.SupplierPromo = supplierPromo
	this.Rid = rid
	this.PpvzSppPrc = ppvzSppPrc
	this.PpvzKvwPrcBase = ppvzKvwPrcBase
	this.PpvzKvwPrc = ppvzKvwPrc
	this.PpvzSalesCommission = ppvzSalesCommission
	this.PpvzForPay = ppvzForPay
	this.PpvzReward = ppvzReward
	this.PpvzVw = ppvzVw
	this.PpvzVwNds = ppvzVwNds
	this.PpvzOfficeId = ppvzOfficeId
	this.PpvzSupplierId = ppvzSupplierId
	return &this
}

// NewInlineResponse2005WithDefaults instantiates a new InlineResponse2005 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2005WithDefaults() *InlineResponse2005 {
	this := InlineResponse2005{}
	return &this
}

// GetRealizationreportId returns the RealizationreportId field value
func (o *InlineResponse2005) GetRealizationreportId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RealizationreportId
}

// GetRealizationreportIdOk returns a tuple with the RealizationreportId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetRealizationreportIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RealizationreportId, true
}

// SetRealizationreportId sets field value
func (o *InlineResponse2005) SetRealizationreportId(v int32) {
	o.RealizationreportId = v
}

// GetSuppliercontractCode returns the SuppliercontractCode field value if set, zero value otherwise.
func (o *InlineResponse2005) GetSuppliercontractCode() int32 {
	if o == nil || o.SuppliercontractCode == nil {
		var ret int32
		return ret
	}
	return *o.SuppliercontractCode
}

// GetSuppliercontractCodeOk returns a tuple with the SuppliercontractCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetSuppliercontractCodeOk() (*int32, bool) {
	if o == nil || o.SuppliercontractCode == nil {
		return nil, false
	}
	return o.SuppliercontractCode, true
}

// HasSuppliercontractCode returns a boolean if a field has been set.
func (o *InlineResponse2005) HasSuppliercontractCode() bool {
	if o != nil && o.SuppliercontractCode != nil {
		return true
	}

	return false
}

// SetSuppliercontractCode gets a reference to the given int32 and assigns it to the SuppliercontractCode field.
func (o *InlineResponse2005) SetSuppliercontractCode(v int32) {
	o.SuppliercontractCode = &v
}

// GetRrdId returns the RrdId field value
func (o *InlineResponse2005) GetRrdId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RrdId
}

// GetRrdIdOk returns a tuple with the RrdId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetRrdIdOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RrdId, true
}

// SetRrdId sets field value
func (o *InlineResponse2005) SetRrdId(v float32) {
	o.RrdId = v
}

// GetGiId returns the GiId field value
func (o *InlineResponse2005) GetGiId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.GiId
}

// GetGiIdOk returns a tuple with the GiId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetGiIdOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.GiId, true
}

// SetGiId sets field value
func (o *InlineResponse2005) SetGiId(v float32) {
	o.GiId = v
}

// GetSubjectName returns the SubjectName field value
func (o *InlineResponse2005) GetSubjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectName
}

// GetSubjectNameOk returns a tuple with the SubjectName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetSubjectNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SubjectName, true
}

// SetSubjectName sets field value
func (o *InlineResponse2005) SetSubjectName(v string) {
	o.SubjectName = v
}

// GetNmId returns the NmId field value
func (o *InlineResponse2005) GetNmId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.NmId
}

// GetNmIdOk returns a tuple with the NmId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetNmIdOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NmId, true
}

// SetNmId sets field value
func (o *InlineResponse2005) SetNmId(v float32) {
	o.NmId = v
}

// GetBrandName returns the BrandName field value
func (o *InlineResponse2005) GetBrandName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BrandName
}

// GetBrandNameOk returns a tuple with the BrandName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetBrandNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BrandName, true
}

// SetBrandName sets field value
func (o *InlineResponse2005) SetBrandName(v string) {
	o.BrandName = v
}

// GetSaName returns the SaName field value
func (o *InlineResponse2005) GetSaName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SaName
}

// GetSaNameOk returns a tuple with the SaName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetSaNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SaName, true
}

// SetSaName sets field value
func (o *InlineResponse2005) SetSaName(v string) {
	o.SaName = v
}

// GetTsName returns the TsName field value
func (o *InlineResponse2005) GetTsName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TsName
}

// GetTsNameOk returns a tuple with the TsName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetTsNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TsName, true
}

// SetTsName sets field value
func (o *InlineResponse2005) SetTsName(v string) {
	o.TsName = v
}

// GetBarcode returns the Barcode field value
func (o *InlineResponse2005) GetBarcode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Barcode
}

// GetBarcodeOk returns a tuple with the Barcode field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetBarcodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Barcode, true
}

// SetBarcode sets field value
func (o *InlineResponse2005) SetBarcode(v string) {
	o.Barcode = v
}

// GetDocTypeName returns the DocTypeName field value
func (o *InlineResponse2005) GetDocTypeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocTypeName
}

// GetDocTypeNameOk returns a tuple with the DocTypeName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetDocTypeNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DocTypeName, true
}

// SetDocTypeName sets field value
func (o *InlineResponse2005) SetDocTypeName(v string) {
	o.DocTypeName = v
}

// GetQuantity returns the Quantity field value
func (o *InlineResponse2005) GetQuantity() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetQuantityOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *InlineResponse2005) SetQuantity(v float32) {
	o.Quantity = v
}

// GetRetailPrice returns the RetailPrice field value
func (o *InlineResponse2005) GetRetailPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RetailPrice
}

// GetRetailPriceOk returns a tuple with the RetailPrice field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetRetailPriceOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RetailPrice, true
}

// SetRetailPrice sets field value
func (o *InlineResponse2005) SetRetailPrice(v float32) {
	o.RetailPrice = v
}

// GetRetailAmount returns the RetailAmount field value
func (o *InlineResponse2005) GetRetailAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RetailAmount
}

// GetRetailAmountOk returns a tuple with the RetailAmount field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetRetailAmountOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RetailAmount, true
}

// SetRetailAmount sets field value
func (o *InlineResponse2005) SetRetailAmount(v float32) {
	o.RetailAmount = v
}

// GetSalePercent returns the SalePercent field value
func (o *InlineResponse2005) GetSalePercent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SalePercent
}

// GetSalePercentOk returns a tuple with the SalePercent field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetSalePercentOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SalePercent, true
}

// SetSalePercent sets field value
func (o *InlineResponse2005) SetSalePercent(v float32) {
	o.SalePercent = v
}

// GetCommissionPercent returns the CommissionPercent field value
func (o *InlineResponse2005) GetCommissionPercent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CommissionPercent
}

// GetCommissionPercentOk returns a tuple with the CommissionPercent field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetCommissionPercentOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CommissionPercent, true
}

// SetCommissionPercent sets field value
func (o *InlineResponse2005) SetCommissionPercent(v float32) {
	o.CommissionPercent = v
}

// GetOfficeName returns the OfficeName field value
func (o *InlineResponse2005) GetOfficeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OfficeName
}

// GetOfficeNameOk returns a tuple with the OfficeName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetOfficeNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OfficeName, true
}

// SetOfficeName sets field value
func (o *InlineResponse2005) SetOfficeName(v string) {
	o.OfficeName = v
}

// GetSupplierOperName returns the SupplierOperName field value
func (o *InlineResponse2005) GetSupplierOperName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SupplierOperName
}

// GetSupplierOperNameOk returns a tuple with the SupplierOperName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetSupplierOperNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SupplierOperName, true
}

// SetSupplierOperName sets field value
func (o *InlineResponse2005) SetSupplierOperName(v string) {
	o.SupplierOperName = v
}

// GetOrderDt returns the OrderDt field value
func (o *InlineResponse2005) GetOrderDt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderDt
}

// GetOrderDtOk returns a tuple with the OrderDt field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetOrderDtOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OrderDt, true
}

// SetOrderDt sets field value
func (o *InlineResponse2005) SetOrderDt(v string) {
	o.OrderDt = v
}

// GetSaleDt returns the SaleDt field value
func (o *InlineResponse2005) GetSaleDt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SaleDt
}

// GetSaleDtOk returns a tuple with the SaleDt field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetSaleDtOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SaleDt, true
}

// SetSaleDt sets field value
func (o *InlineResponse2005) SetSaleDt(v string) {
	o.SaleDt = v
}

// GetRrDt returns the RrDt field value
func (o *InlineResponse2005) GetRrDt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RrDt
}

// GetRrDtOk returns a tuple with the RrDt field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetRrDtOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RrDt, true
}

// SetRrDt sets field value
func (o *InlineResponse2005) SetRrDt(v string) {
	o.RrDt = v
}

// GetShkId returns the ShkId field value
func (o *InlineResponse2005) GetShkId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ShkId
}

// GetShkIdOk returns a tuple with the ShkId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetShkIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ShkId, true
}

// SetShkId sets field value
func (o *InlineResponse2005) SetShkId(v int32) {
	o.ShkId = v
}

// GetRetailPriceWithdiscRub returns the RetailPriceWithdiscRub field value
func (o *InlineResponse2005) GetRetailPriceWithdiscRub() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RetailPriceWithdiscRub
}

// GetRetailPriceWithdiscRubOk returns a tuple with the RetailPriceWithdiscRub field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetRetailPriceWithdiscRubOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RetailPriceWithdiscRub, true
}

// SetRetailPriceWithdiscRub sets field value
func (o *InlineResponse2005) SetRetailPriceWithdiscRub(v float32) {
	o.RetailPriceWithdiscRub = v
}

// GetDeliveryAmount returns the DeliveryAmount field value
func (o *InlineResponse2005) GetDeliveryAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DeliveryAmount
}

// GetDeliveryAmountOk returns a tuple with the DeliveryAmount field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetDeliveryAmountOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DeliveryAmount, true
}

// SetDeliveryAmount sets field value
func (o *InlineResponse2005) SetDeliveryAmount(v float32) {
	o.DeliveryAmount = v
}

// GetReturnAmount returns the ReturnAmount field value
func (o *InlineResponse2005) GetReturnAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ReturnAmount
}

// GetReturnAmountOk returns a tuple with the ReturnAmount field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetReturnAmountOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ReturnAmount, true
}

// SetReturnAmount sets field value
func (o *InlineResponse2005) SetReturnAmount(v float32) {
	o.ReturnAmount = v
}

// GetDeliveryRub returns the DeliveryRub field value
func (o *InlineResponse2005) GetDeliveryRub() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DeliveryRub
}

// GetDeliveryRubOk returns a tuple with the DeliveryRub field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetDeliveryRubOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DeliveryRub, true
}

// SetDeliveryRub sets field value
func (o *InlineResponse2005) SetDeliveryRub(v float32) {
	o.DeliveryRub = v
}

// GetGiBoxTypeName returns the GiBoxTypeName field value
func (o *InlineResponse2005) GetGiBoxTypeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GiBoxTypeName
}

// GetGiBoxTypeNameOk returns a tuple with the GiBoxTypeName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetGiBoxTypeNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.GiBoxTypeName, true
}

// SetGiBoxTypeName sets field value
func (o *InlineResponse2005) SetGiBoxTypeName(v string) {
	o.GiBoxTypeName = v
}

// GetProductDiscountForReport returns the ProductDiscountForReport field value
func (o *InlineResponse2005) GetProductDiscountForReport() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ProductDiscountForReport
}

// GetProductDiscountForReportOk returns a tuple with the ProductDiscountForReport field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetProductDiscountForReportOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ProductDiscountForReport, true
}

// SetProductDiscountForReport sets field value
func (o *InlineResponse2005) SetProductDiscountForReport(v float32) {
	o.ProductDiscountForReport = v
}

// GetSupplierPromo returns the SupplierPromo field value
func (o *InlineResponse2005) GetSupplierPromo() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SupplierPromo
}

// GetSupplierPromoOk returns a tuple with the SupplierPromo field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetSupplierPromoOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SupplierPromo, true
}

// SetSupplierPromo sets field value
func (o *InlineResponse2005) SetSupplierPromo(v float32) {
	o.SupplierPromo = v
}

// GetRid returns the Rid field value
func (o *InlineResponse2005) GetRid() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Rid
}

// GetRidOk returns a tuple with the Rid field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetRidOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Rid, true
}

// SetRid sets field value
func (o *InlineResponse2005) SetRid(v int32) {
	o.Rid = v
}

// GetPpvzSppPrc returns the PpvzSppPrc field value
func (o *InlineResponse2005) GetPpvzSppPrc() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzSppPrc
}

// GetPpvzSppPrcOk returns a tuple with the PpvzSppPrc field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzSppPrcOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PpvzSppPrc, true
}

// SetPpvzSppPrc sets field value
func (o *InlineResponse2005) SetPpvzSppPrc(v float32) {
	o.PpvzSppPrc = v
}

// GetPpvzKvwPrcBase returns the PpvzKvwPrcBase field value
func (o *InlineResponse2005) GetPpvzKvwPrcBase() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzKvwPrcBase
}

// GetPpvzKvwPrcBaseOk returns a tuple with the PpvzKvwPrcBase field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzKvwPrcBaseOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PpvzKvwPrcBase, true
}

// SetPpvzKvwPrcBase sets field value
func (o *InlineResponse2005) SetPpvzKvwPrcBase(v float32) {
	o.PpvzKvwPrcBase = v
}

// GetPpvzKvwPrc returns the PpvzKvwPrc field value
func (o *InlineResponse2005) GetPpvzKvwPrc() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzKvwPrc
}

// GetPpvzKvwPrcOk returns a tuple with the PpvzKvwPrc field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzKvwPrcOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PpvzKvwPrc, true
}

// SetPpvzKvwPrc sets field value
func (o *InlineResponse2005) SetPpvzKvwPrc(v float32) {
	o.PpvzKvwPrc = v
}

// GetPpvzSalesCommission returns the PpvzSalesCommission field value
func (o *InlineResponse2005) GetPpvzSalesCommission() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzSalesCommission
}

// GetPpvzSalesCommissionOk returns a tuple with the PpvzSalesCommission field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzSalesCommissionOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PpvzSalesCommission, true
}

// SetPpvzSalesCommission sets field value
func (o *InlineResponse2005) SetPpvzSalesCommission(v float32) {
	o.PpvzSalesCommission = v
}

// GetPpvzForPay returns the PpvzForPay field value
func (o *InlineResponse2005) GetPpvzForPay() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzForPay
}

// GetPpvzForPayOk returns a tuple with the PpvzForPay field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzForPayOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PpvzForPay, true
}

// SetPpvzForPay sets field value
func (o *InlineResponse2005) SetPpvzForPay(v float32) {
	o.PpvzForPay = v
}

// GetPpvzReward returns the PpvzReward field value
func (o *InlineResponse2005) GetPpvzReward() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzReward
}

// GetPpvzRewardOk returns a tuple with the PpvzReward field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzRewardOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PpvzReward, true
}

// SetPpvzReward sets field value
func (o *InlineResponse2005) SetPpvzReward(v float32) {
	o.PpvzReward = v
}

// GetPpvzVw returns the PpvzVw field value
func (o *InlineResponse2005) GetPpvzVw() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzVw
}

// GetPpvzVwOk returns a tuple with the PpvzVw field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzVwOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PpvzVw, true
}

// SetPpvzVw sets field value
func (o *InlineResponse2005) SetPpvzVw(v float32) {
	o.PpvzVw = v
}

// GetPpvzVwNds returns the PpvzVwNds field value
func (o *InlineResponse2005) GetPpvzVwNds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzVwNds
}

// GetPpvzVwNdsOk returns a tuple with the PpvzVwNds field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzVwNdsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PpvzVwNds, true
}

// SetPpvzVwNds sets field value
func (o *InlineResponse2005) SetPpvzVwNds(v float32) {
	o.PpvzVwNds = v
}

// GetPpvzOfficeId returns the PpvzOfficeId field value
func (o *InlineResponse2005) GetPpvzOfficeId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PpvzOfficeId
}

// GetPpvzOfficeIdOk returns a tuple with the PpvzOfficeId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzOfficeIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PpvzOfficeId, true
}

// SetPpvzOfficeId sets field value
func (o *InlineResponse2005) SetPpvzOfficeId(v int32) {
	o.PpvzOfficeId = v
}

// GetPpvzOfficeName returns the PpvzOfficeName field value if set, zero value otherwise.
func (o *InlineResponse2005) GetPpvzOfficeName() string {
	if o == nil || o.PpvzOfficeName == nil {
		var ret string
		return ret
	}
	return *o.PpvzOfficeName
}

// GetPpvzOfficeNameOk returns a tuple with the PpvzOfficeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzOfficeNameOk() (*string, bool) {
	if o == nil || o.PpvzOfficeName == nil {
		return nil, false
	}
	return o.PpvzOfficeName, true
}

// HasPpvzOfficeName returns a boolean if a field has been set.
func (o *InlineResponse2005) HasPpvzOfficeName() bool {
	if o != nil && o.PpvzOfficeName != nil {
		return true
	}

	return false
}

// SetPpvzOfficeName gets a reference to the given string and assigns it to the PpvzOfficeName field.
func (o *InlineResponse2005) SetPpvzOfficeName(v string) {
	o.PpvzOfficeName = &v
}

// GetPpvzSupplierId returns the PpvzSupplierId field value
func (o *InlineResponse2005) GetPpvzSupplierId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PpvzSupplierId
}

// GetPpvzSupplierIdOk returns a tuple with the PpvzSupplierId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzSupplierIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PpvzSupplierId, true
}

// SetPpvzSupplierId sets field value
func (o *InlineResponse2005) SetPpvzSupplierId(v int32) {
	o.PpvzSupplierId = v
}

// GetPpvzSupplierName returns the PpvzSupplierName field value if set, zero value otherwise.
func (o *InlineResponse2005) GetPpvzSupplierName() string {
	if o == nil || o.PpvzSupplierName == nil {
		var ret string
		return ret
	}
	return *o.PpvzSupplierName
}

// GetPpvzSupplierNameOk returns a tuple with the PpvzSupplierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzSupplierNameOk() (*string, bool) {
	if o == nil || o.PpvzSupplierName == nil {
		return nil, false
	}
	return o.PpvzSupplierName, true
}

// HasPpvzSupplierName returns a boolean if a field has been set.
func (o *InlineResponse2005) HasPpvzSupplierName() bool {
	if o != nil && o.PpvzSupplierName != nil {
		return true
	}

	return false
}

// SetPpvzSupplierName gets a reference to the given string and assigns it to the PpvzSupplierName field.
func (o *InlineResponse2005) SetPpvzSupplierName(v string) {
	o.PpvzSupplierName = &v
}

// GetPpvzSupplierInn returns the PpvzSupplierInn field value if set, zero value otherwise.
func (o *InlineResponse2005) GetPpvzSupplierInn() string {
	if o == nil || o.PpvzSupplierInn == nil {
		var ret string
		return ret
	}
	return *o.PpvzSupplierInn
}

// GetPpvzSupplierInnOk returns a tuple with the PpvzSupplierInn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2005) GetPpvzSupplierInnOk() (*string, bool) {
	if o == nil || o.PpvzSupplierInn == nil {
		return nil, false
	}
	return o.PpvzSupplierInn, true
}

// HasPpvzSupplierInn returns a boolean if a field has been set.
func (o *InlineResponse2005) HasPpvzSupplierInn() bool {
	if o != nil && o.PpvzSupplierInn != nil {
		return true
	}

	return false
}

// SetPpvzSupplierInn gets a reference to the given string and assigns it to the PpvzSupplierInn field.
func (o *InlineResponse2005) SetPpvzSupplierInn(v string) {
	o.PpvzSupplierInn = &v
}

func (o InlineResponse2005) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["realizationreport_id"] = o.RealizationreportId
	}
	if o.SuppliercontractCode != nil {
		toSerialize["suppliercontract_code"] = o.SuppliercontractCode
	}
	if true {
		toSerialize["rrd_id"] = o.RrdId
	}
	if true {
		toSerialize["gi_id"] = o.GiId
	}
	if true {
		toSerialize["subject_name"] = o.SubjectName
	}
	if true {
		toSerialize["nm_id"] = o.NmId
	}
	if true {
		toSerialize["brand_name"] = o.BrandName
	}
	if true {
		toSerialize["sa_name"] = o.SaName
	}
	if true {
		toSerialize["ts_name"] = o.TsName
	}
	if true {
		toSerialize["barcode"] = o.Barcode
	}
	if true {
		toSerialize["doc_type_name"] = o.DocTypeName
	}
	if true {
		toSerialize["quantity"] = o.Quantity
	}
	if true {
		toSerialize["retail_price"] = o.RetailPrice
	}
	if true {
		toSerialize["retail_amount"] = o.RetailAmount
	}
	if true {
		toSerialize["sale_percent"] = o.SalePercent
	}
	if true {
		toSerialize["commission_percent"] = o.CommissionPercent
	}
	if true {
		toSerialize["office_name"] = o.OfficeName
	}
	if true {
		toSerialize["supplier_oper_name"] = o.SupplierOperName
	}
	if true {
		toSerialize["order_dt"] = o.OrderDt
	}
	if true {
		toSerialize["sale_dt"] = o.SaleDt
	}
	if true {
		toSerialize["rr_dt"] = o.RrDt
	}
	if true {
		toSerialize["shk_id"] = o.ShkId
	}
	if true {
		toSerialize["retail_price_withdisc_rub"] = o.RetailPriceWithdiscRub
	}
	if true {
		toSerialize["delivery_amount"] = o.DeliveryAmount
	}
	if true {
		toSerialize["return_amount"] = o.ReturnAmount
	}
	if true {
		toSerialize["delivery_rub"] = o.DeliveryRub
	}
	if true {
		toSerialize["gi_box_type_name"] = o.GiBoxTypeName
	}
	if true {
		toSerialize["product_discount_for_report"] = o.ProductDiscountForReport
	}
	if true {
		toSerialize["supplier_promo"] = o.SupplierPromo
	}
	if true {
		toSerialize["rid"] = o.Rid
	}
	if true {
		toSerialize["ppvz_spp_prc"] = o.PpvzSppPrc
	}
	if true {
		toSerialize["ppvz_kvw_prc_base"] = o.PpvzKvwPrcBase
	}
	if true {
		toSerialize["ppvz_kvw_prc"] = o.PpvzKvwPrc
	}
	if true {
		toSerialize["ppvz_sales_commission"] = o.PpvzSalesCommission
	}
	if true {
		toSerialize["ppvz_for_pay"] = o.PpvzForPay
	}
	if true {
		toSerialize["ppvz_reward"] = o.PpvzReward
	}
	if true {
		toSerialize["ppvz_vw"] = o.PpvzVw
	}
	if true {
		toSerialize["ppvz_vw_nds"] = o.PpvzVwNds
	}
	if true {
		toSerialize["ppvz_office_id"] = o.PpvzOfficeId
	}
	if o.PpvzOfficeName != nil {
		toSerialize["ppvz_office_name"] = o.PpvzOfficeName
	}
	if true {
		toSerialize["ppvz_supplier_id"] = o.PpvzSupplierId
	}
	if o.PpvzSupplierName != nil {
		toSerialize["ppvz_supplier_name"] = o.PpvzSupplierName
	}
	if o.PpvzSupplierInn != nil {
		toSerialize["ppvz_supplier_inn"] = o.PpvzSupplierInn
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2005 struct {
	value *InlineResponse2005
	isSet bool
}

func (v NullableInlineResponse2005) Get() *InlineResponse2005 {
	return v.value
}

func (v *NullableInlineResponse2005) Set(val *InlineResponse2005) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2005) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2005) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2005(val *InlineResponse2005) *NullableInlineResponse2005 {
	return &NullableInlineResponse2005{value: val, isSet: true}
}

func (v NullableInlineResponse2005) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2005) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


