/*
WB Supplier Stats

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse2002 struct for InlineResponse2002
type InlineResponse2002 struct {
	// Дата и время обновления данных в сервисе
	LastChangeDate string `json:"lastChangeDate"`
	// Артикул продавца
	SupplierArticle string `json:"supplierArticle"`
	// Размер
	TechSize string `json:"techSize"`
	// Штрих-код
	Barcode string `json:"barcode"`
	// Количество доступное для продажи
	Quantity int64 `json:"quantity"`
	// Договор поставки
	IsSupply bool `json:"isSupply"`
	// Договор реализации
	IsRealization bool `json:"isRealization"`
	// Полное количество
	QuantityFull int64 `json:"quantityFull"`
	// Количество не в заказе
	QuantityNotInOrders int64 `json:"quantityNotInOrders"`
	// Название склада
	WarehouseName string `json:"warehouseName"`
	// Количество штук в пути к клиенту
	InWayToClient int32 `json:"inWayToClient"`
	// Количество штук в пути от клиента
	InWayFromClient int32 `json:"inWayFromClient"`
	// Код wildberries
	NmId int64 `json:"nmId"`
	// Предмет
	Subject string `json:"subject"`
	// Категория
	Category string `json:"category"`
	// Количество дней на сайте
	DaysOnSite int32 `json:"daysOnSite"`
	// Бренд
	Brand string `json:"brand"`
	// Код контракта
	SCCode string `json:"SCCode"`
	// Цена (?)
	Price float32 `json:"Price"`
	// Скидка (?)
	Discount float32 `json:"Discount"`
}

// NewInlineResponse2002 instantiates a new InlineResponse2002 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2002(lastChangeDate string, supplierArticle string, techSize string, barcode string, quantity int64, isSupply bool, isRealization bool, quantityFull int64, quantityNotInOrders int64, warehouseName string, inWayToClient int32, inWayFromClient int32, nmId int64, subject string, category string, daysOnSite int32, brand string, sCCode string, price float32, discount float32) *InlineResponse2002 {
	this := InlineResponse2002{}
	this.LastChangeDate = lastChangeDate
	this.SupplierArticle = supplierArticle
	this.TechSize = techSize
	this.Barcode = barcode
	this.Quantity = quantity
	this.IsSupply = isSupply
	this.IsRealization = isRealization
	this.QuantityFull = quantityFull
	this.QuantityNotInOrders = quantityNotInOrders
	this.WarehouseName = warehouseName
	this.InWayToClient = inWayToClient
	this.InWayFromClient = inWayFromClient
	this.NmId = nmId
	this.Subject = subject
	this.Category = category
	this.DaysOnSite = daysOnSite
	this.Brand = brand
	this.SCCode = sCCode
	this.Price = price
	this.Discount = discount
	return &this
}

// NewInlineResponse2002WithDefaults instantiates a new InlineResponse2002 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2002WithDefaults() *InlineResponse2002 {
	this := InlineResponse2002{}
	return &this
}

// GetLastChangeDate returns the LastChangeDate field value
func (o *InlineResponse2002) GetLastChangeDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastChangeDate
}

// GetLastChangeDateOk returns a tuple with the LastChangeDate field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetLastChangeDateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastChangeDate, true
}

// SetLastChangeDate sets field value
func (o *InlineResponse2002) SetLastChangeDate(v string) {
	o.LastChangeDate = v
}

// GetSupplierArticle returns the SupplierArticle field value
func (o *InlineResponse2002) GetSupplierArticle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SupplierArticle
}

// GetSupplierArticleOk returns a tuple with the SupplierArticle field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetSupplierArticleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SupplierArticle, true
}

// SetSupplierArticle sets field value
func (o *InlineResponse2002) SetSupplierArticle(v string) {
	o.SupplierArticle = v
}

// GetTechSize returns the TechSize field value
func (o *InlineResponse2002) GetTechSize() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TechSize
}

// GetTechSizeOk returns a tuple with the TechSize field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetTechSizeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TechSize, true
}

// SetTechSize sets field value
func (o *InlineResponse2002) SetTechSize(v string) {
	o.TechSize = v
}

// GetBarcode returns the Barcode field value
func (o *InlineResponse2002) GetBarcode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Barcode
}

// GetBarcodeOk returns a tuple with the Barcode field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetBarcodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Barcode, true
}

// SetBarcode sets field value
func (o *InlineResponse2002) SetBarcode(v string) {
	o.Barcode = v
}

// GetQuantity returns the Quantity field value
func (o *InlineResponse2002) GetQuantity() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetQuantityOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *InlineResponse2002) SetQuantity(v int64) {
	o.Quantity = v
}

// GetIsSupply returns the IsSupply field value
func (o *InlineResponse2002) GetIsSupply() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSupply
}

// GetIsSupplyOk returns a tuple with the IsSupply field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetIsSupplyOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsSupply, true
}

// SetIsSupply sets field value
func (o *InlineResponse2002) SetIsSupply(v bool) {
	o.IsSupply = v
}

// GetIsRealization returns the IsRealization field value
func (o *InlineResponse2002) GetIsRealization() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsRealization
}

// GetIsRealizationOk returns a tuple with the IsRealization field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetIsRealizationOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsRealization, true
}

// SetIsRealization sets field value
func (o *InlineResponse2002) SetIsRealization(v bool) {
	o.IsRealization = v
}

// GetQuantityFull returns the QuantityFull field value
func (o *InlineResponse2002) GetQuantityFull() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.QuantityFull
}

// GetQuantityFullOk returns a tuple with the QuantityFull field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetQuantityFullOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.QuantityFull, true
}

// SetQuantityFull sets field value
func (o *InlineResponse2002) SetQuantityFull(v int64) {
	o.QuantityFull = v
}

// GetQuantityNotInOrders returns the QuantityNotInOrders field value
func (o *InlineResponse2002) GetQuantityNotInOrders() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.QuantityNotInOrders
}

// GetQuantityNotInOrdersOk returns a tuple with the QuantityNotInOrders field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetQuantityNotInOrdersOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.QuantityNotInOrders, true
}

// SetQuantityNotInOrders sets field value
func (o *InlineResponse2002) SetQuantityNotInOrders(v int64) {
	o.QuantityNotInOrders = v
}

// GetWarehouseName returns the WarehouseName field value
func (o *InlineResponse2002) GetWarehouseName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WarehouseName
}

// GetWarehouseNameOk returns a tuple with the WarehouseName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetWarehouseNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WarehouseName, true
}

// SetWarehouseName sets field value
func (o *InlineResponse2002) SetWarehouseName(v string) {
	o.WarehouseName = v
}

// GetInWayToClient returns the InWayToClient field value
func (o *InlineResponse2002) GetInWayToClient() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InWayToClient
}

// GetInWayToClientOk returns a tuple with the InWayToClient field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetInWayToClientOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.InWayToClient, true
}

// SetInWayToClient sets field value
func (o *InlineResponse2002) SetInWayToClient(v int32) {
	o.InWayToClient = v
}

// GetInWayFromClient returns the InWayFromClient field value
func (o *InlineResponse2002) GetInWayFromClient() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InWayFromClient
}

// GetInWayFromClientOk returns a tuple with the InWayFromClient field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetInWayFromClientOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.InWayFromClient, true
}

// SetInWayFromClient sets field value
func (o *InlineResponse2002) SetInWayFromClient(v int32) {
	o.InWayFromClient = v
}

// GetNmId returns the NmId field value
func (o *InlineResponse2002) GetNmId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NmId
}

// GetNmIdOk returns a tuple with the NmId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetNmIdOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NmId, true
}

// SetNmId sets field value
func (o *InlineResponse2002) SetNmId(v int64) {
	o.NmId = v
}

// GetSubject returns the Subject field value
func (o *InlineResponse2002) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetSubjectOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *InlineResponse2002) SetSubject(v string) {
	o.Subject = v
}

// GetCategory returns the Category field value
func (o *InlineResponse2002) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetCategoryOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *InlineResponse2002) SetCategory(v string) {
	o.Category = v
}

// GetDaysOnSite returns the DaysOnSite field value
func (o *InlineResponse2002) GetDaysOnSite() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DaysOnSite
}

// GetDaysOnSiteOk returns a tuple with the DaysOnSite field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetDaysOnSiteOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DaysOnSite, true
}

// SetDaysOnSite sets field value
func (o *InlineResponse2002) SetDaysOnSite(v int32) {
	o.DaysOnSite = v
}

// GetBrand returns the Brand field value
func (o *InlineResponse2002) GetBrand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Brand
}

// GetBrandOk returns a tuple with the Brand field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetBrandOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Brand, true
}

// SetBrand sets field value
func (o *InlineResponse2002) SetBrand(v string) {
	o.Brand = v
}

// GetSCCode returns the SCCode field value
func (o *InlineResponse2002) GetSCCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SCCode
}

// GetSCCodeOk returns a tuple with the SCCode field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetSCCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SCCode, true
}

// SetSCCode sets field value
func (o *InlineResponse2002) SetSCCode(v string) {
	o.SCCode = v
}

// GetPrice returns the Price field value
func (o *InlineResponse2002) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetPriceOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *InlineResponse2002) SetPrice(v float32) {
	o.Price = v
}

// GetDiscount returns the Discount field value
func (o *InlineResponse2002) GetDiscount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetDiscountOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Discount, true
}

// SetDiscount sets field value
func (o *InlineResponse2002) SetDiscount(v float32) {
	o.Discount = v
}

func (o InlineResponse2002) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["lastChangeDate"] = o.LastChangeDate
	}
	if true {
		toSerialize["supplierArticle"] = o.SupplierArticle
	}
	if true {
		toSerialize["techSize"] = o.TechSize
	}
	if true {
		toSerialize["barcode"] = o.Barcode
	}
	if true {
		toSerialize["quantity"] = o.Quantity
	}
	if true {
		toSerialize["isSupply"] = o.IsSupply
	}
	if true {
		toSerialize["isRealization"] = o.IsRealization
	}
	if true {
		toSerialize["quantityFull"] = o.QuantityFull
	}
	if true {
		toSerialize["quantityNotInOrders"] = o.QuantityNotInOrders
	}
	if true {
		toSerialize["warehouseName"] = o.WarehouseName
	}
	if true {
		toSerialize["inWayToClient"] = o.InWayToClient
	}
	if true {
		toSerialize["inWayFromClient"] = o.InWayFromClient
	}
	if true {
		toSerialize["nmId"] = o.NmId
	}
	if true {
		toSerialize["subject"] = o.Subject
	}
	if true {
		toSerialize["category"] = o.Category
	}
	if true {
		toSerialize["daysOnSite"] = o.DaysOnSite
	}
	if true {
		toSerialize["brand"] = o.Brand
	}
	if true {
		toSerialize["SCCode"] = o.SCCode
	}
	if true {
		toSerialize["Price"] = o.Price
	}
	if true {
		toSerialize["Discount"] = o.Discount
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2002 struct {
	value *InlineResponse2002
	isSet bool
}

func (v NullableInlineResponse2002) Get() *InlineResponse2002 {
	return v.value
}

func (v *NullableInlineResponse2002) Set(val *InlineResponse2002) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2002) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2002) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2002(val *InlineResponse2002) *NullableInlineResponse2002 {
	return &NullableInlineResponse2002{value: val, isSet: true}
}

func (v NullableInlineResponse2002) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2002) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


