/*
WB Supplier Stats

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	
)

// checks if the GetStocks200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStocks200ResponseInner{}

// GetStocks200ResponseInner struct for GetStocks200ResponseInner
type GetStocks200ResponseInner struct {
	// Дата и время обновления данных в сервисе
	LastChangeDate StockTime `json:"lastChangeDate"`
	// Артикул продавца
	SupplierArticle string `json:"supplierArticle"`
	// Размер
	TechSize string `json:"techSize"`
	// Штрих-код
	Barcode string `json:"barcode"`
	// Количество доступное для продажи
	Quantity int64 `json:"quantity"`
	// Договор поставки
	IsSupply bool `json:"isSupply"`
	// Договор реализации
	IsRealization bool `json:"isRealization"`
	// Полное количество
	QuantityFull int64 `json:"quantityFull"`
	// Название склада
	WarehouseName string `json:"warehouseName"`
	// Код wildberries
	NmId int64 `json:"nmId"`
	// Предмет
	Subject string `json:"subject"`
	// Категория
	Category string `json:"category"`
	// Количество дней на сайте
	DaysOnSite int32 `json:"daysOnSite"`
	// Бренд
	Brand string `json:"brand"`
	// Код контракта
	SCCode string `json:"SCCode"`
	// Цена (?)
	Price float32 `json:"Price"`
	// Скидка (?)
	Discount float32 `json:"Discount"`
}

// NewGetStocks200ResponseInner instantiates a new GetStocks200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStocks200ResponseInner(lastChangeDate StockTime, supplierArticle string, techSize string, barcode string, quantity int64, isSupply bool, isRealization bool, quantityFull int64, warehouseName string, nmId int64, subject string, category string, daysOnSite int32, brand string, sCCode string, price float32, discount float32) *GetStocks200ResponseInner {
	this := GetStocks200ResponseInner{}
	this.LastChangeDate = lastChangeDate
	this.SupplierArticle = supplierArticle
	this.TechSize = techSize
	this.Barcode = barcode
	this.Quantity = quantity
	this.IsSupply = isSupply
	this.IsRealization = isRealization
	this.QuantityFull = quantityFull
	this.WarehouseName = warehouseName
	this.NmId = nmId
	this.Subject = subject
	this.Category = category
	this.DaysOnSite = daysOnSite
	this.Brand = brand
	this.SCCode = sCCode
	this.Price = price
	this.Discount = discount
	return &this
}

// NewGetStocks200ResponseInnerWithDefaults instantiates a new GetStocks200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStocks200ResponseInnerWithDefaults() *GetStocks200ResponseInner {
	this := GetStocks200ResponseInner{}
	return &this
}

// GetLastChangeDate returns the LastChangeDate field value
func (o *GetStocks200ResponseInner) GetLastChangeDate() StockTime {
	if o == nil {
		var ret StockTime
		return ret
	}

	return o.LastChangeDate
}

// GetLastChangeDateOk returns a tuple with the LastChangeDate field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetLastChangeDateOk() (*StockTime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastChangeDate, true
}

// SetLastChangeDate sets field value
func (o *GetStocks200ResponseInner) SetLastChangeDate(v StockTime) {
	o.LastChangeDate = v
}

// GetSupplierArticle returns the SupplierArticle field value
func (o *GetStocks200ResponseInner) GetSupplierArticle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SupplierArticle
}

// GetSupplierArticleOk returns a tuple with the SupplierArticle field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetSupplierArticleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SupplierArticle, true
}

// SetSupplierArticle sets field value
func (o *GetStocks200ResponseInner) SetSupplierArticle(v string) {
	o.SupplierArticle = v
}

// GetTechSize returns the TechSize field value
func (o *GetStocks200ResponseInner) GetTechSize() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TechSize
}

// GetTechSizeOk returns a tuple with the TechSize field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetTechSizeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TechSize, true
}

// SetTechSize sets field value
func (o *GetStocks200ResponseInner) SetTechSize(v string) {
	o.TechSize = v
}

// GetBarcode returns the Barcode field value
func (o *GetStocks200ResponseInner) GetBarcode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Barcode
}

// GetBarcodeOk returns a tuple with the Barcode field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetBarcodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Barcode, true
}

// SetBarcode sets field value
func (o *GetStocks200ResponseInner) SetBarcode(v string) {
	o.Barcode = v
}

// GetQuantity returns the Quantity field value
func (o *GetStocks200ResponseInner) GetQuantity() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetQuantityOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *GetStocks200ResponseInner) SetQuantity(v int64) {
	o.Quantity = v
}

// GetIsSupply returns the IsSupply field value
func (o *GetStocks200ResponseInner) GetIsSupply() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSupply
}

// GetIsSupplyOk returns a tuple with the IsSupply field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetIsSupplyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsSupply, true
}

// SetIsSupply sets field value
func (o *GetStocks200ResponseInner) SetIsSupply(v bool) {
	o.IsSupply = v
}

// GetIsRealization returns the IsRealization field value
func (o *GetStocks200ResponseInner) GetIsRealization() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsRealization
}

// GetIsRealizationOk returns a tuple with the IsRealization field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetIsRealizationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsRealization, true
}

// SetIsRealization sets field value
func (o *GetStocks200ResponseInner) SetIsRealization(v bool) {
	o.IsRealization = v
}

// GetQuantityFull returns the QuantityFull field value
func (o *GetStocks200ResponseInner) GetQuantityFull() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.QuantityFull
}

// GetQuantityFullOk returns a tuple with the QuantityFull field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetQuantityFullOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuantityFull, true
}

// SetQuantityFull sets field value
func (o *GetStocks200ResponseInner) SetQuantityFull(v int64) {
	o.QuantityFull = v
}

// GetWarehouseName returns the WarehouseName field value
func (o *GetStocks200ResponseInner) GetWarehouseName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WarehouseName
}

// GetWarehouseNameOk returns a tuple with the WarehouseName field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetWarehouseNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WarehouseName, true
}

// SetWarehouseName sets field value
func (o *GetStocks200ResponseInner) SetWarehouseName(v string) {
	o.WarehouseName = v
}

// GetNmId returns the NmId field value
func (o *GetStocks200ResponseInner) GetNmId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NmId
}

// GetNmIdOk returns a tuple with the NmId field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetNmIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NmId, true
}

// SetNmId sets field value
func (o *GetStocks200ResponseInner) SetNmId(v int64) {
	o.NmId = v
}

// GetSubject returns the Subject field value
func (o *GetStocks200ResponseInner) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *GetStocks200ResponseInner) SetSubject(v string) {
	o.Subject = v
}

// GetCategory returns the Category field value
func (o *GetStocks200ResponseInner) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *GetStocks200ResponseInner) SetCategory(v string) {
	o.Category = v
}

// GetDaysOnSite returns the DaysOnSite field value
func (o *GetStocks200ResponseInner) GetDaysOnSite() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DaysOnSite
}

// GetDaysOnSiteOk returns a tuple with the DaysOnSite field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetDaysOnSiteOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DaysOnSite, true
}

// SetDaysOnSite sets field value
func (o *GetStocks200ResponseInner) SetDaysOnSite(v int32) {
	o.DaysOnSite = v
}

// GetBrand returns the Brand field value
func (o *GetStocks200ResponseInner) GetBrand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Brand
}

// GetBrandOk returns a tuple with the Brand field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetBrandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Brand, true
}

// SetBrand sets field value
func (o *GetStocks200ResponseInner) SetBrand(v string) {
	o.Brand = v
}

// GetSCCode returns the SCCode field value
func (o *GetStocks200ResponseInner) GetSCCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SCCode
}

// GetSCCodeOk returns a tuple with the SCCode field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetSCCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SCCode, true
}

// SetSCCode sets field value
func (o *GetStocks200ResponseInner) SetSCCode(v string) {
	o.SCCode = v
}

// GetPrice returns the Price field value
func (o *GetStocks200ResponseInner) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *GetStocks200ResponseInner) SetPrice(v float32) {
	o.Price = v
}

// GetDiscount returns the Discount field value
func (o *GetStocks200ResponseInner) GetDiscount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value
// and a boolean to check if the value has been set.
func (o *GetStocks200ResponseInner) GetDiscountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Discount, true
}

// SetDiscount sets field value
func (o *GetStocks200ResponseInner) SetDiscount(v float32) {
	o.Discount = v
}

func (o GetStocks200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStocks200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lastChangeDate"] = o.LastChangeDate
	toSerialize["supplierArticle"] = o.SupplierArticle
	toSerialize["techSize"] = o.TechSize
	toSerialize["barcode"] = o.Barcode
	toSerialize["quantity"] = o.Quantity
	toSerialize["isSupply"] = o.IsSupply
	toSerialize["isRealization"] = o.IsRealization
	toSerialize["quantityFull"] = o.QuantityFull
	toSerialize["warehouseName"] = o.WarehouseName
	toSerialize["nmId"] = o.NmId
	toSerialize["subject"] = o.Subject
	toSerialize["category"] = o.Category
	toSerialize["daysOnSite"] = o.DaysOnSite
	toSerialize["brand"] = o.Brand
	toSerialize["SCCode"] = o.SCCode
	toSerialize["Price"] = o.Price
	toSerialize["Discount"] = o.Discount
	return toSerialize, nil
}

type NullableGetStocks200ResponseInner struct {
	value *GetStocks200ResponseInner
	isSet bool
}

func (v NullableGetStocks200ResponseInner) Get() *GetStocks200ResponseInner {
	return v.value
}

func (v *NullableGetStocks200ResponseInner) Set(val *GetStocks200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStocks200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStocks200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStocks200ResponseInner(val *GetStocks200ResponseInner) *NullableGetStocks200ResponseInner {
	return &NullableGetStocks200ResponseInner{value: val, isSet: true}
}

func (v NullableGetStocks200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStocks200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


