/*
WB Supplier Stats

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the GetReportDetailByPeriod200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReportDetailByPeriod200ResponseInner{}

// GetReportDetailByPeriod200ResponseInner struct for GetReportDetailByPeriod200ResponseInner
type GetReportDetailByPeriod200ResponseInner struct {
	// Дата начала отчётного периода
	DateFrom *time.Time `json:"date_from,omitempty"`
	// Дата конца отчётного периода
	DateTo *time.Time `json:"date_to,omitempty"`
	// Дата формирования отчёта
	CreateDt *time.Time `json:"create_dt,omitempty"`
	// Размер снижения кВВ из-за рейтинга, %
	SupRatingPrcUp *float32 `json:"sup_rating_prc_up,omitempty"`
	// Размер снижения кВВ из-за акции, %
	IsKgvpV2 *float32 `json:"is_kgvp_v2,omitempty"`
	// Возмещение расходов по эквайрингу. Расходы WB на услуги эквайринга: вычитаются из вознаграждения WB и не влияют на доход продавца
	AcquiringFee *float32 `json:"acquiring_fee,omitempty"`
	// Наименование банка, предоставляющего услуги эквайринг
	AcquiringBank *string `json:"acquiring_bank,omitempty"`
	// Обоснование штрафов и доплат
	BonusTypeName *string `json:"bonus_type_name,omitempty"`
	// Код маркировки
	Kiz *string `json:"kiz,omitempty"`
	// Идентификатор отчёта
	RealizationreportId int32 `json:"realizationreport_id"`
	// Договор
	SuppliercontractCode *int32 `json:"suppliercontract_code,omitempty"`
	// Идентификатор записи
	RrdId int64 `json:"rrd_id"`
	// Идентификатор поставки
	GiId int64 `json:"gi_id"`
	// Наименование товара
	SubjectName string `json:"subject_name"`
	// SKU товара
	NmId *int64 `json:"nm_id,omitempty"`
	// Бренд товара
	BrandName string `json:"brand_name"`
	// Артикул поставщика
	SaName string `json:"sa_name"`
	// Размер
	TsName string `json:"ts_name"`
	// Баркод
	Barcode string `json:"barcode"`
	// Тип документа
	DocTypeName string `json:"doc_type_name"`
	// Количество
	Quantity int32 `json:"quantity"`
	// Розничная цена
	RetailPrice float32 `json:"retail_price"`
	// Сумма продаж (возвратов)
	RetailAmount float32 `json:"retail_amount"`
	// Согласованная скидка
	SalePercent float32 `json:"sale_percent"`
	// Процент комиссии
	CommissionPercent float32 `json:"commission_percent"`
	// Наименование склада
	OfficeName string `json:"office_name"`
	// Обоснование для оплаты (Тип операции?)
	SupplierOperName string `json:"supplier_oper_name"`
	// Дата заказа
	OrderDt *string `json:"order_dt,omitempty"`
	// Дата продажи
	SaleDt *string `json:"sale_dt,omitempty"`
	// Дата операции
	RrDt string `json:"rr_dt"`
	// Штрих код (короба?)
	ShkId int64 `json:"shk_id"`
	// Розничная цена с учётом согласованной скидки
	RetailPriceWithdiscRub *float32 `json:"retail_price_withdisc_rub,omitempty"`
	// Количество доставок
	DeliveryAmount *int32 `json:"delivery_amount,omitempty"`
	// Количество возвратов
	ReturnAmount *int32 `json:"return_amount,omitempty"`
	// Стоимость логистики
	DeliveryRub *float32 `json:"delivery_rub,omitempty"`
	// Тип коробов
	GiBoxTypeName string `json:"gi_box_type_name"`
	// Согласованный продуктовый дисконт
	ProductDiscountForReport *float32 `json:"product_discount_for_report,omitempty"`
	// Промокод
	SupplierPromo *float32 `json:"supplier_promo,omitempty"`
	// Идентификатор заказа
	Rid *int64 `json:"rid,omitempty"`
	// Скидка постоянного покупателя
	PpvzSppPrc float32 `json:"ppvz_spp_prc"`
	// Базовый размер коэффициента вознаграждения вайлдберриз без НДС, %
	PpvzKvwPrcBase float32 `json:"ppvz_kvw_prc_base"`
	// Итоговый размер коэффициента вознаграждения вайлдберриз без НДС, %
	PpvzKvwPrc float32 `json:"ppvz_kvw_prc"`
	// Вознаграждение с продаж до вычета услуг поверенного, без НДС
	PpvzSalesCommission float32 `json:"ppvz_sales_commission"`
	// К перечислению продавцу за реализованный Товар
	PpvzForPay float32 `json:"ppvz_for_pay"`
	// Возмещение расходов услуг поверенного
	PpvzReward float32 `json:"ppvz_reward"`
	// Вознаграждение вайлдберриз, без НДС
	PpvzVw float32 `json:"ppvz_vw"`
	// НДС с вознаграждения вайлдберриз
	PpvzVwNds float32 `json:"ppvz_vw_nds"`
	// Идентификатор ПВЗ?
	PpvzOfficeId int64 `json:"ppvz_office_id"`
	// Наименование ПВЗ? (в случае если ppvz_office_id = 0)
	PpvzOfficeName *string `json:"ppvz_office_name,omitempty"`
	// Идентификатор владельца ПВЗ?
	PpvzSupplierId int64 `json:"ppvz_supplier_id"`
	// Наименование владельца ПВЗ
	PpvzSupplierName *string `json:"ppvz_supplier_name,omitempty"`
	// ИНН владельца ПВЗ
	PpvzSupplierInn *string `json:"ppvz_supplier_inn,omitempty"`
	// Номер таможенной декларации
	DeclarationNumber *string `json:"declaration_number,omitempty"`
	// Цифровое значение стикера, который клеится на товар в процессе сборки заказа по системе Маркетплейс.
	StickerId *string `json:"sticker_id,omitempty"`
	// Страна продажи
	SiteCountry *string `json:"site_country,omitempty"`
	// Штрафы
	Penalty float32 `json:"penalty"`
	// Доплаты
	AdditionalPayment float32 `json:"additional_payment"`
	// Новый идентификатор заказа
	Srid *string `json:"srid,omitempty"`
}

// NewGetReportDetailByPeriod200ResponseInner instantiates a new GetReportDetailByPeriod200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReportDetailByPeriod200ResponseInner(realizationreportId int32, rrdId int64, giId int64, subjectName string, brandName string, saName string, tsName string, barcode string, docTypeName string, quantity int32, retailPrice float32, retailAmount float32, salePercent float32, commissionPercent float32, officeName string, supplierOperName string, rrDt string, shkId int64, giBoxTypeName string, ppvzSppPrc float32, ppvzKvwPrcBase float32, ppvzKvwPrc float32, ppvzSalesCommission float32, ppvzForPay float32, ppvzReward float32, ppvzVw float32, ppvzVwNds float32, ppvzOfficeId int64, ppvzSupplierId int64, penalty float32, additionalPayment float32) *GetReportDetailByPeriod200ResponseInner {
	this := GetReportDetailByPeriod200ResponseInner{}
	this.RealizationreportId = realizationreportId
	this.RrdId = rrdId
	this.GiId = giId
	this.SubjectName = subjectName
	this.BrandName = brandName
	this.SaName = saName
	this.TsName = tsName
	this.Barcode = barcode
	this.DocTypeName = docTypeName
	this.Quantity = quantity
	this.RetailPrice = retailPrice
	this.RetailAmount = retailAmount
	this.SalePercent = salePercent
	this.CommissionPercent = commissionPercent
	this.OfficeName = officeName
	this.SupplierOperName = supplierOperName
	this.RrDt = rrDt
	this.ShkId = shkId
	this.GiBoxTypeName = giBoxTypeName
	this.PpvzSppPrc = ppvzSppPrc
	this.PpvzKvwPrcBase = ppvzKvwPrcBase
	this.PpvzKvwPrc = ppvzKvwPrc
	this.PpvzSalesCommission = ppvzSalesCommission
	this.PpvzForPay = ppvzForPay
	this.PpvzReward = ppvzReward
	this.PpvzVw = ppvzVw
	this.PpvzVwNds = ppvzVwNds
	this.PpvzOfficeId = ppvzOfficeId
	this.PpvzSupplierId = ppvzSupplierId
	this.Penalty = penalty
	this.AdditionalPayment = additionalPayment
	return &this
}

// NewGetReportDetailByPeriod200ResponseInnerWithDefaults instantiates a new GetReportDetailByPeriod200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReportDetailByPeriod200ResponseInnerWithDefaults() *GetReportDetailByPeriod200ResponseInner {
	this := GetReportDetailByPeriod200ResponseInner{}
	return &this
}

// GetDateFrom returns the DateFrom field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetDateFrom() time.Time {
	if o == nil || isNil(o.DateFrom) {
		var ret time.Time
		return ret
	}
	return *o.DateFrom
}

// GetDateFromOk returns a tuple with the DateFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetDateFromOk() (*time.Time, bool) {
	if o == nil || isNil(o.DateFrom) {
		return nil, false
	}
	return o.DateFrom, true
}

// HasDateFrom returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasDateFrom() bool {
	if o != nil && !isNil(o.DateFrom) {
		return true
	}

	return false
}

// SetDateFrom gets a reference to the given time.Time and assigns it to the DateFrom field.
func (o *GetReportDetailByPeriod200ResponseInner) SetDateFrom(v time.Time) {
	o.DateFrom = &v
}

// GetDateTo returns the DateTo field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetDateTo() time.Time {
	if o == nil || isNil(o.DateTo) {
		var ret time.Time
		return ret
	}
	return *o.DateTo
}

// GetDateToOk returns a tuple with the DateTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetDateToOk() (*time.Time, bool) {
	if o == nil || isNil(o.DateTo) {
		return nil, false
	}
	return o.DateTo, true
}

// HasDateTo returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasDateTo() bool {
	if o != nil && !isNil(o.DateTo) {
		return true
	}

	return false
}

// SetDateTo gets a reference to the given time.Time and assigns it to the DateTo field.
func (o *GetReportDetailByPeriod200ResponseInner) SetDateTo(v time.Time) {
	o.DateTo = &v
}

// GetCreateDt returns the CreateDt field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetCreateDt() time.Time {
	if o == nil || isNil(o.CreateDt) {
		var ret time.Time
		return ret
	}
	return *o.CreateDt
}

// GetCreateDtOk returns a tuple with the CreateDt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetCreateDtOk() (*time.Time, bool) {
	if o == nil || isNil(o.CreateDt) {
		return nil, false
	}
	return o.CreateDt, true
}

// HasCreateDt returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasCreateDt() bool {
	if o != nil && !isNil(o.CreateDt) {
		return true
	}

	return false
}

// SetCreateDt gets a reference to the given time.Time and assigns it to the CreateDt field.
func (o *GetReportDetailByPeriod200ResponseInner) SetCreateDt(v time.Time) {
	o.CreateDt = &v
}

// GetSupRatingPrcUp returns the SupRatingPrcUp field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetSupRatingPrcUp() float32 {
	if o == nil || isNil(o.SupRatingPrcUp) {
		var ret float32
		return ret
	}
	return *o.SupRatingPrcUp
}

// GetSupRatingPrcUpOk returns a tuple with the SupRatingPrcUp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetSupRatingPrcUpOk() (*float32, bool) {
	if o == nil || isNil(o.SupRatingPrcUp) {
		return nil, false
	}
	return o.SupRatingPrcUp, true
}

// HasSupRatingPrcUp returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasSupRatingPrcUp() bool {
	if o != nil && !isNil(o.SupRatingPrcUp) {
		return true
	}

	return false
}

// SetSupRatingPrcUp gets a reference to the given float32 and assigns it to the SupRatingPrcUp field.
func (o *GetReportDetailByPeriod200ResponseInner) SetSupRatingPrcUp(v float32) {
	o.SupRatingPrcUp = &v
}

// GetIsKgvpV2 returns the IsKgvpV2 field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetIsKgvpV2() float32 {
	if o == nil || isNil(o.IsKgvpV2) {
		var ret float32
		return ret
	}
	return *o.IsKgvpV2
}

// GetIsKgvpV2Ok returns a tuple with the IsKgvpV2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetIsKgvpV2Ok() (*float32, bool) {
	if o == nil || isNil(o.IsKgvpV2) {
		return nil, false
	}
	return o.IsKgvpV2, true
}

// HasIsKgvpV2 returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasIsKgvpV2() bool {
	if o != nil && !isNil(o.IsKgvpV2) {
		return true
	}

	return false
}

// SetIsKgvpV2 gets a reference to the given float32 and assigns it to the IsKgvpV2 field.
func (o *GetReportDetailByPeriod200ResponseInner) SetIsKgvpV2(v float32) {
	o.IsKgvpV2 = &v
}

// GetAcquiringFee returns the AcquiringFee field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetAcquiringFee() float32 {
	if o == nil || isNil(o.AcquiringFee) {
		var ret float32
		return ret
	}
	return *o.AcquiringFee
}

// GetAcquiringFeeOk returns a tuple with the AcquiringFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetAcquiringFeeOk() (*float32, bool) {
	if o == nil || isNil(o.AcquiringFee) {
		return nil, false
	}
	return o.AcquiringFee, true
}

// HasAcquiringFee returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasAcquiringFee() bool {
	if o != nil && !isNil(o.AcquiringFee) {
		return true
	}

	return false
}

// SetAcquiringFee gets a reference to the given float32 and assigns it to the AcquiringFee field.
func (o *GetReportDetailByPeriod200ResponseInner) SetAcquiringFee(v float32) {
	o.AcquiringFee = &v
}

// GetAcquiringBank returns the AcquiringBank field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetAcquiringBank() string {
	if o == nil || isNil(o.AcquiringBank) {
		var ret string
		return ret
	}
	return *o.AcquiringBank
}

// GetAcquiringBankOk returns a tuple with the AcquiringBank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetAcquiringBankOk() (*string, bool) {
	if o == nil || isNil(o.AcquiringBank) {
		return nil, false
	}
	return o.AcquiringBank, true
}

// HasAcquiringBank returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasAcquiringBank() bool {
	if o != nil && !isNil(o.AcquiringBank) {
		return true
	}

	return false
}

// SetAcquiringBank gets a reference to the given string and assigns it to the AcquiringBank field.
func (o *GetReportDetailByPeriod200ResponseInner) SetAcquiringBank(v string) {
	o.AcquiringBank = &v
}

// GetBonusTypeName returns the BonusTypeName field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetBonusTypeName() string {
	if o == nil || isNil(o.BonusTypeName) {
		var ret string
		return ret
	}
	return *o.BonusTypeName
}

// GetBonusTypeNameOk returns a tuple with the BonusTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetBonusTypeNameOk() (*string, bool) {
	if o == nil || isNil(o.BonusTypeName) {
		return nil, false
	}
	return o.BonusTypeName, true
}

// HasBonusTypeName returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasBonusTypeName() bool {
	if o != nil && !isNil(o.BonusTypeName) {
		return true
	}

	return false
}

// SetBonusTypeName gets a reference to the given string and assigns it to the BonusTypeName field.
func (o *GetReportDetailByPeriod200ResponseInner) SetBonusTypeName(v string) {
	o.BonusTypeName = &v
}

// GetKiz returns the Kiz field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetKiz() string {
	if o == nil || isNil(o.Kiz) {
		var ret string
		return ret
	}
	return *o.Kiz
}

// GetKizOk returns a tuple with the Kiz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetKizOk() (*string, bool) {
	if o == nil || isNil(o.Kiz) {
		return nil, false
	}
	return o.Kiz, true
}

// HasKiz returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasKiz() bool {
	if o != nil && !isNil(o.Kiz) {
		return true
	}

	return false
}

// SetKiz gets a reference to the given string and assigns it to the Kiz field.
func (o *GetReportDetailByPeriod200ResponseInner) SetKiz(v string) {
	o.Kiz = &v
}

// GetRealizationreportId returns the RealizationreportId field value
func (o *GetReportDetailByPeriod200ResponseInner) GetRealizationreportId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RealizationreportId
}

// GetRealizationreportIdOk returns a tuple with the RealizationreportId field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetRealizationreportIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RealizationreportId, true
}

// SetRealizationreportId sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetRealizationreportId(v int32) {
	o.RealizationreportId = v
}

// GetSuppliercontractCode returns the SuppliercontractCode field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetSuppliercontractCode() int32 {
	if o == nil || isNil(o.SuppliercontractCode) {
		var ret int32
		return ret
	}
	return *o.SuppliercontractCode
}

// GetSuppliercontractCodeOk returns a tuple with the SuppliercontractCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetSuppliercontractCodeOk() (*int32, bool) {
	if o == nil || isNil(o.SuppliercontractCode) {
		return nil, false
	}
	return o.SuppliercontractCode, true
}

// HasSuppliercontractCode returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasSuppliercontractCode() bool {
	if o != nil && !isNil(o.SuppliercontractCode) {
		return true
	}

	return false
}

// SetSuppliercontractCode gets a reference to the given int32 and assigns it to the SuppliercontractCode field.
func (o *GetReportDetailByPeriod200ResponseInner) SetSuppliercontractCode(v int32) {
	o.SuppliercontractCode = &v
}

// GetRrdId returns the RrdId field value
func (o *GetReportDetailByPeriod200ResponseInner) GetRrdId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RrdId
}

// GetRrdIdOk returns a tuple with the RrdId field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetRrdIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RrdId, true
}

// SetRrdId sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetRrdId(v int64) {
	o.RrdId = v
}

// GetGiId returns the GiId field value
func (o *GetReportDetailByPeriod200ResponseInner) GetGiId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.GiId
}

// GetGiIdOk returns a tuple with the GiId field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetGiIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GiId, true
}

// SetGiId sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetGiId(v int64) {
	o.GiId = v
}

// GetSubjectName returns the SubjectName field value
func (o *GetReportDetailByPeriod200ResponseInner) GetSubjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectName
}

// GetSubjectNameOk returns a tuple with the SubjectName field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetSubjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectName, true
}

// SetSubjectName sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetSubjectName(v string) {
	o.SubjectName = v
}

// GetNmId returns the NmId field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetNmId() int64 {
	if o == nil || isNil(o.NmId) {
		var ret int64
		return ret
	}
	return *o.NmId
}

// GetNmIdOk returns a tuple with the NmId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetNmIdOk() (*int64, bool) {
	if o == nil || isNil(o.NmId) {
		return nil, false
	}
	return o.NmId, true
}

// HasNmId returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasNmId() bool {
	if o != nil && !isNil(o.NmId) {
		return true
	}

	return false
}

// SetNmId gets a reference to the given int64 and assigns it to the NmId field.
func (o *GetReportDetailByPeriod200ResponseInner) SetNmId(v int64) {
	o.NmId = &v
}

// GetBrandName returns the BrandName field value
func (o *GetReportDetailByPeriod200ResponseInner) GetBrandName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BrandName
}

// GetBrandNameOk returns a tuple with the BrandName field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetBrandNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BrandName, true
}

// SetBrandName sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetBrandName(v string) {
	o.BrandName = v
}

// GetSaName returns the SaName field value
func (o *GetReportDetailByPeriod200ResponseInner) GetSaName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SaName
}

// GetSaNameOk returns a tuple with the SaName field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetSaNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SaName, true
}

// SetSaName sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetSaName(v string) {
	o.SaName = v
}

// GetTsName returns the TsName field value
func (o *GetReportDetailByPeriod200ResponseInner) GetTsName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TsName
}

// GetTsNameOk returns a tuple with the TsName field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetTsNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TsName, true
}

// SetTsName sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetTsName(v string) {
	o.TsName = v
}

// GetBarcode returns the Barcode field value
func (o *GetReportDetailByPeriod200ResponseInner) GetBarcode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Barcode
}

// GetBarcodeOk returns a tuple with the Barcode field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetBarcodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Barcode, true
}

// SetBarcode sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetBarcode(v string) {
	o.Barcode = v
}

// GetDocTypeName returns the DocTypeName field value
func (o *GetReportDetailByPeriod200ResponseInner) GetDocTypeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocTypeName
}

// GetDocTypeNameOk returns a tuple with the DocTypeName field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetDocTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocTypeName, true
}

// SetDocTypeName sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetDocTypeName(v string) {
	o.DocTypeName = v
}

// GetQuantity returns the Quantity field value
func (o *GetReportDetailByPeriod200ResponseInner) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetQuantity(v int32) {
	o.Quantity = v
}

// GetRetailPrice returns the RetailPrice field value
func (o *GetReportDetailByPeriod200ResponseInner) GetRetailPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RetailPrice
}

// GetRetailPriceOk returns a tuple with the RetailPrice field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetRetailPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetailPrice, true
}

// SetRetailPrice sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetRetailPrice(v float32) {
	o.RetailPrice = v
}

// GetRetailAmount returns the RetailAmount field value
func (o *GetReportDetailByPeriod200ResponseInner) GetRetailAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RetailAmount
}

// GetRetailAmountOk returns a tuple with the RetailAmount field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetRetailAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetailAmount, true
}

// SetRetailAmount sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetRetailAmount(v float32) {
	o.RetailAmount = v
}

// GetSalePercent returns the SalePercent field value
func (o *GetReportDetailByPeriod200ResponseInner) GetSalePercent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SalePercent
}

// GetSalePercentOk returns a tuple with the SalePercent field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetSalePercentOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SalePercent, true
}

// SetSalePercent sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetSalePercent(v float32) {
	o.SalePercent = v
}

// GetCommissionPercent returns the CommissionPercent field value
func (o *GetReportDetailByPeriod200ResponseInner) GetCommissionPercent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CommissionPercent
}

// GetCommissionPercentOk returns a tuple with the CommissionPercent field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetCommissionPercentOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommissionPercent, true
}

// SetCommissionPercent sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetCommissionPercent(v float32) {
	o.CommissionPercent = v
}

// GetOfficeName returns the OfficeName field value
func (o *GetReportDetailByPeriod200ResponseInner) GetOfficeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OfficeName
}

// GetOfficeNameOk returns a tuple with the OfficeName field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetOfficeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfficeName, true
}

// SetOfficeName sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetOfficeName(v string) {
	o.OfficeName = v
}

// GetSupplierOperName returns the SupplierOperName field value
func (o *GetReportDetailByPeriod200ResponseInner) GetSupplierOperName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SupplierOperName
}

// GetSupplierOperNameOk returns a tuple with the SupplierOperName field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetSupplierOperNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SupplierOperName, true
}

// SetSupplierOperName sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetSupplierOperName(v string) {
	o.SupplierOperName = v
}

// GetOrderDt returns the OrderDt field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetOrderDt() string {
	if o == nil || isNil(o.OrderDt) {
		var ret string
		return ret
	}
	return *o.OrderDt
}

// GetOrderDtOk returns a tuple with the OrderDt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetOrderDtOk() (*string, bool) {
	if o == nil || isNil(o.OrderDt) {
		return nil, false
	}
	return o.OrderDt, true
}

// HasOrderDt returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasOrderDt() bool {
	if o != nil && !isNil(o.OrderDt) {
		return true
	}

	return false
}

// SetOrderDt gets a reference to the given string and assigns it to the OrderDt field.
func (o *GetReportDetailByPeriod200ResponseInner) SetOrderDt(v string) {
	o.OrderDt = &v
}

// GetSaleDt returns the SaleDt field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetSaleDt() string {
	if o == nil || isNil(o.SaleDt) {
		var ret string
		return ret
	}
	return *o.SaleDt
}

// GetSaleDtOk returns a tuple with the SaleDt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetSaleDtOk() (*string, bool) {
	if o == nil || isNil(o.SaleDt) {
		return nil, false
	}
	return o.SaleDt, true
}

// HasSaleDt returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasSaleDt() bool {
	if o != nil && !isNil(o.SaleDt) {
		return true
	}

	return false
}

// SetSaleDt gets a reference to the given string and assigns it to the SaleDt field.
func (o *GetReportDetailByPeriod200ResponseInner) SetSaleDt(v string) {
	o.SaleDt = &v
}

// GetRrDt returns the RrDt field value
func (o *GetReportDetailByPeriod200ResponseInner) GetRrDt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RrDt
}

// GetRrDtOk returns a tuple with the RrDt field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetRrDtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RrDt, true
}

// SetRrDt sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetRrDt(v string) {
	o.RrDt = v
}

// GetShkId returns the ShkId field value
func (o *GetReportDetailByPeriod200ResponseInner) GetShkId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ShkId
}

// GetShkIdOk returns a tuple with the ShkId field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetShkIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShkId, true
}

// SetShkId sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetShkId(v int64) {
	o.ShkId = v
}

// GetRetailPriceWithdiscRub returns the RetailPriceWithdiscRub field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetRetailPriceWithdiscRub() float32 {
	if o == nil || isNil(o.RetailPriceWithdiscRub) {
		var ret float32
		return ret
	}
	return *o.RetailPriceWithdiscRub
}

// GetRetailPriceWithdiscRubOk returns a tuple with the RetailPriceWithdiscRub field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetRetailPriceWithdiscRubOk() (*float32, bool) {
	if o == nil || isNil(o.RetailPriceWithdiscRub) {
		return nil, false
	}
	return o.RetailPriceWithdiscRub, true
}

// HasRetailPriceWithdiscRub returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasRetailPriceWithdiscRub() bool {
	if o != nil && !isNil(o.RetailPriceWithdiscRub) {
		return true
	}

	return false
}

// SetRetailPriceWithdiscRub gets a reference to the given float32 and assigns it to the RetailPriceWithdiscRub field.
func (o *GetReportDetailByPeriod200ResponseInner) SetRetailPriceWithdiscRub(v float32) {
	o.RetailPriceWithdiscRub = &v
}

// GetDeliveryAmount returns the DeliveryAmount field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetDeliveryAmount() int32 {
	if o == nil || isNil(o.DeliveryAmount) {
		var ret int32
		return ret
	}
	return *o.DeliveryAmount
}

// GetDeliveryAmountOk returns a tuple with the DeliveryAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetDeliveryAmountOk() (*int32, bool) {
	if o == nil || isNil(o.DeliveryAmount) {
		return nil, false
	}
	return o.DeliveryAmount, true
}

// HasDeliveryAmount returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasDeliveryAmount() bool {
	if o != nil && !isNil(o.DeliveryAmount) {
		return true
	}

	return false
}

// SetDeliveryAmount gets a reference to the given int32 and assigns it to the DeliveryAmount field.
func (o *GetReportDetailByPeriod200ResponseInner) SetDeliveryAmount(v int32) {
	o.DeliveryAmount = &v
}

// GetReturnAmount returns the ReturnAmount field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetReturnAmount() int32 {
	if o == nil || isNil(o.ReturnAmount) {
		var ret int32
		return ret
	}
	return *o.ReturnAmount
}

// GetReturnAmountOk returns a tuple with the ReturnAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetReturnAmountOk() (*int32, bool) {
	if o == nil || isNil(o.ReturnAmount) {
		return nil, false
	}
	return o.ReturnAmount, true
}

// HasReturnAmount returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasReturnAmount() bool {
	if o != nil && !isNil(o.ReturnAmount) {
		return true
	}

	return false
}

// SetReturnAmount gets a reference to the given int32 and assigns it to the ReturnAmount field.
func (o *GetReportDetailByPeriod200ResponseInner) SetReturnAmount(v int32) {
	o.ReturnAmount = &v
}

// GetDeliveryRub returns the DeliveryRub field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetDeliveryRub() float32 {
	if o == nil || isNil(o.DeliveryRub) {
		var ret float32
		return ret
	}
	return *o.DeliveryRub
}

// GetDeliveryRubOk returns a tuple with the DeliveryRub field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetDeliveryRubOk() (*float32, bool) {
	if o == nil || isNil(o.DeliveryRub) {
		return nil, false
	}
	return o.DeliveryRub, true
}

// HasDeliveryRub returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasDeliveryRub() bool {
	if o != nil && !isNil(o.DeliveryRub) {
		return true
	}

	return false
}

// SetDeliveryRub gets a reference to the given float32 and assigns it to the DeliveryRub field.
func (o *GetReportDetailByPeriod200ResponseInner) SetDeliveryRub(v float32) {
	o.DeliveryRub = &v
}

// GetGiBoxTypeName returns the GiBoxTypeName field value
func (o *GetReportDetailByPeriod200ResponseInner) GetGiBoxTypeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GiBoxTypeName
}

// GetGiBoxTypeNameOk returns a tuple with the GiBoxTypeName field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetGiBoxTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GiBoxTypeName, true
}

// SetGiBoxTypeName sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetGiBoxTypeName(v string) {
	o.GiBoxTypeName = v
}

// GetProductDiscountForReport returns the ProductDiscountForReport field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetProductDiscountForReport() float32 {
	if o == nil || isNil(o.ProductDiscountForReport) {
		var ret float32
		return ret
	}
	return *o.ProductDiscountForReport
}

// GetProductDiscountForReportOk returns a tuple with the ProductDiscountForReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetProductDiscountForReportOk() (*float32, bool) {
	if o == nil || isNil(o.ProductDiscountForReport) {
		return nil, false
	}
	return o.ProductDiscountForReport, true
}

// HasProductDiscountForReport returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasProductDiscountForReport() bool {
	if o != nil && !isNil(o.ProductDiscountForReport) {
		return true
	}

	return false
}

// SetProductDiscountForReport gets a reference to the given float32 and assigns it to the ProductDiscountForReport field.
func (o *GetReportDetailByPeriod200ResponseInner) SetProductDiscountForReport(v float32) {
	o.ProductDiscountForReport = &v
}

// GetSupplierPromo returns the SupplierPromo field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetSupplierPromo() float32 {
	if o == nil || isNil(o.SupplierPromo) {
		var ret float32
		return ret
	}
	return *o.SupplierPromo
}

// GetSupplierPromoOk returns a tuple with the SupplierPromo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetSupplierPromoOk() (*float32, bool) {
	if o == nil || isNil(o.SupplierPromo) {
		return nil, false
	}
	return o.SupplierPromo, true
}

// HasSupplierPromo returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasSupplierPromo() bool {
	if o != nil && !isNil(o.SupplierPromo) {
		return true
	}

	return false
}

// SetSupplierPromo gets a reference to the given float32 and assigns it to the SupplierPromo field.
func (o *GetReportDetailByPeriod200ResponseInner) SetSupplierPromo(v float32) {
	o.SupplierPromo = &v
}

// GetRid returns the Rid field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetRid() int64 {
	if o == nil || isNil(o.Rid) {
		var ret int64
		return ret
	}
	return *o.Rid
}

// GetRidOk returns a tuple with the Rid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetRidOk() (*int64, bool) {
	if o == nil || isNil(o.Rid) {
		return nil, false
	}
	return o.Rid, true
}

// HasRid returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasRid() bool {
	if o != nil && !isNil(o.Rid) {
		return true
	}

	return false
}

// SetRid gets a reference to the given int64 and assigns it to the Rid field.
func (o *GetReportDetailByPeriod200ResponseInner) SetRid(v int64) {
	o.Rid = &v
}

// GetPpvzSppPrc returns the PpvzSppPrc field value
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzSppPrc() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzSppPrc
}

// GetPpvzSppPrcOk returns a tuple with the PpvzSppPrc field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzSppPrcOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PpvzSppPrc, true
}

// SetPpvzSppPrc sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzSppPrc(v float32) {
	o.PpvzSppPrc = v
}

// GetPpvzKvwPrcBase returns the PpvzKvwPrcBase field value
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzKvwPrcBase() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzKvwPrcBase
}

// GetPpvzKvwPrcBaseOk returns a tuple with the PpvzKvwPrcBase field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzKvwPrcBaseOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PpvzKvwPrcBase, true
}

// SetPpvzKvwPrcBase sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzKvwPrcBase(v float32) {
	o.PpvzKvwPrcBase = v
}

// GetPpvzKvwPrc returns the PpvzKvwPrc field value
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzKvwPrc() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzKvwPrc
}

// GetPpvzKvwPrcOk returns a tuple with the PpvzKvwPrc field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzKvwPrcOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PpvzKvwPrc, true
}

// SetPpvzKvwPrc sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzKvwPrc(v float32) {
	o.PpvzKvwPrc = v
}

// GetPpvzSalesCommission returns the PpvzSalesCommission field value
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzSalesCommission() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzSalesCommission
}

// GetPpvzSalesCommissionOk returns a tuple with the PpvzSalesCommission field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzSalesCommissionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PpvzSalesCommission, true
}

// SetPpvzSalesCommission sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzSalesCommission(v float32) {
	o.PpvzSalesCommission = v
}

// GetPpvzForPay returns the PpvzForPay field value
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzForPay() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzForPay
}

// GetPpvzForPayOk returns a tuple with the PpvzForPay field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzForPayOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PpvzForPay, true
}

// SetPpvzForPay sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzForPay(v float32) {
	o.PpvzForPay = v
}

// GetPpvzReward returns the PpvzReward field value
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzReward() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzReward
}

// GetPpvzRewardOk returns a tuple with the PpvzReward field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzRewardOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PpvzReward, true
}

// SetPpvzReward sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzReward(v float32) {
	o.PpvzReward = v
}

// GetPpvzVw returns the PpvzVw field value
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzVw() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzVw
}

// GetPpvzVwOk returns a tuple with the PpvzVw field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzVwOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PpvzVw, true
}

// SetPpvzVw sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzVw(v float32) {
	o.PpvzVw = v
}

// GetPpvzVwNds returns the PpvzVwNds field value
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzVwNds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PpvzVwNds
}

// GetPpvzVwNdsOk returns a tuple with the PpvzVwNds field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzVwNdsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PpvzVwNds, true
}

// SetPpvzVwNds sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzVwNds(v float32) {
	o.PpvzVwNds = v
}

// GetPpvzOfficeId returns the PpvzOfficeId field value
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzOfficeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PpvzOfficeId
}

// GetPpvzOfficeIdOk returns a tuple with the PpvzOfficeId field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzOfficeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PpvzOfficeId, true
}

// SetPpvzOfficeId sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzOfficeId(v int64) {
	o.PpvzOfficeId = v
}

// GetPpvzOfficeName returns the PpvzOfficeName field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzOfficeName() string {
	if o == nil || isNil(o.PpvzOfficeName) {
		var ret string
		return ret
	}
	return *o.PpvzOfficeName
}

// GetPpvzOfficeNameOk returns a tuple with the PpvzOfficeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzOfficeNameOk() (*string, bool) {
	if o == nil || isNil(o.PpvzOfficeName) {
		return nil, false
	}
	return o.PpvzOfficeName, true
}

// HasPpvzOfficeName returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasPpvzOfficeName() bool {
	if o != nil && !isNil(o.PpvzOfficeName) {
		return true
	}

	return false
}

// SetPpvzOfficeName gets a reference to the given string and assigns it to the PpvzOfficeName field.
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzOfficeName(v string) {
	o.PpvzOfficeName = &v
}

// GetPpvzSupplierId returns the PpvzSupplierId field value
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzSupplierId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PpvzSupplierId
}

// GetPpvzSupplierIdOk returns a tuple with the PpvzSupplierId field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzSupplierIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PpvzSupplierId, true
}

// SetPpvzSupplierId sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzSupplierId(v int64) {
	o.PpvzSupplierId = v
}

// GetPpvzSupplierName returns the PpvzSupplierName field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzSupplierName() string {
	if o == nil || isNil(o.PpvzSupplierName) {
		var ret string
		return ret
	}
	return *o.PpvzSupplierName
}

// GetPpvzSupplierNameOk returns a tuple with the PpvzSupplierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzSupplierNameOk() (*string, bool) {
	if o == nil || isNil(o.PpvzSupplierName) {
		return nil, false
	}
	return o.PpvzSupplierName, true
}

// HasPpvzSupplierName returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasPpvzSupplierName() bool {
	if o != nil && !isNil(o.PpvzSupplierName) {
		return true
	}

	return false
}

// SetPpvzSupplierName gets a reference to the given string and assigns it to the PpvzSupplierName field.
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzSupplierName(v string) {
	o.PpvzSupplierName = &v
}

// GetPpvzSupplierInn returns the PpvzSupplierInn field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzSupplierInn() string {
	if o == nil || isNil(o.PpvzSupplierInn) {
		var ret string
		return ret
	}
	return *o.PpvzSupplierInn
}

// GetPpvzSupplierInnOk returns a tuple with the PpvzSupplierInn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPpvzSupplierInnOk() (*string, bool) {
	if o == nil || isNil(o.PpvzSupplierInn) {
		return nil, false
	}
	return o.PpvzSupplierInn, true
}

// HasPpvzSupplierInn returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasPpvzSupplierInn() bool {
	if o != nil && !isNil(o.PpvzSupplierInn) {
		return true
	}

	return false
}

// SetPpvzSupplierInn gets a reference to the given string and assigns it to the PpvzSupplierInn field.
func (o *GetReportDetailByPeriod200ResponseInner) SetPpvzSupplierInn(v string) {
	o.PpvzSupplierInn = &v
}

// GetDeclarationNumber returns the DeclarationNumber field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetDeclarationNumber() string {
	if o == nil || isNil(o.DeclarationNumber) {
		var ret string
		return ret
	}
	return *o.DeclarationNumber
}

// GetDeclarationNumberOk returns a tuple with the DeclarationNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetDeclarationNumberOk() (*string, bool) {
	if o == nil || isNil(o.DeclarationNumber) {
		return nil, false
	}
	return o.DeclarationNumber, true
}

// HasDeclarationNumber returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasDeclarationNumber() bool {
	if o != nil && !isNil(o.DeclarationNumber) {
		return true
	}

	return false
}

// SetDeclarationNumber gets a reference to the given string and assigns it to the DeclarationNumber field.
func (o *GetReportDetailByPeriod200ResponseInner) SetDeclarationNumber(v string) {
	o.DeclarationNumber = &v
}

// GetStickerId returns the StickerId field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetStickerId() string {
	if o == nil || isNil(o.StickerId) {
		var ret string
		return ret
	}
	return *o.StickerId
}

// GetStickerIdOk returns a tuple with the StickerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetStickerIdOk() (*string, bool) {
	if o == nil || isNil(o.StickerId) {
		return nil, false
	}
	return o.StickerId, true
}

// HasStickerId returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasStickerId() bool {
	if o != nil && !isNil(o.StickerId) {
		return true
	}

	return false
}

// SetStickerId gets a reference to the given string and assigns it to the StickerId field.
func (o *GetReportDetailByPeriod200ResponseInner) SetStickerId(v string) {
	o.StickerId = &v
}

// GetSiteCountry returns the SiteCountry field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetSiteCountry() string {
	if o == nil || isNil(o.SiteCountry) {
		var ret string
		return ret
	}
	return *o.SiteCountry
}

// GetSiteCountryOk returns a tuple with the SiteCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetSiteCountryOk() (*string, bool) {
	if o == nil || isNil(o.SiteCountry) {
		return nil, false
	}
	return o.SiteCountry, true
}

// HasSiteCountry returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasSiteCountry() bool {
	if o != nil && !isNil(o.SiteCountry) {
		return true
	}

	return false
}

// SetSiteCountry gets a reference to the given string and assigns it to the SiteCountry field.
func (o *GetReportDetailByPeriod200ResponseInner) SetSiteCountry(v string) {
	o.SiteCountry = &v
}

// GetPenalty returns the Penalty field value
func (o *GetReportDetailByPeriod200ResponseInner) GetPenalty() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Penalty
}

// GetPenaltyOk returns a tuple with the Penalty field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetPenaltyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Penalty, true
}

// SetPenalty sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetPenalty(v float32) {
	o.Penalty = v
}

// GetAdditionalPayment returns the AdditionalPayment field value
func (o *GetReportDetailByPeriod200ResponseInner) GetAdditionalPayment() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AdditionalPayment
}

// GetAdditionalPaymentOk returns a tuple with the AdditionalPayment field value
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetAdditionalPaymentOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdditionalPayment, true
}

// SetAdditionalPayment sets field value
func (o *GetReportDetailByPeriod200ResponseInner) SetAdditionalPayment(v float32) {
	o.AdditionalPayment = v
}

// GetSrid returns the Srid field value if set, zero value otherwise.
func (o *GetReportDetailByPeriod200ResponseInner) GetSrid() string {
	if o == nil || isNil(o.Srid) {
		var ret string
		return ret
	}
	return *o.Srid
}

// GetSridOk returns a tuple with the Srid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportDetailByPeriod200ResponseInner) GetSridOk() (*string, bool) {
	if o == nil || isNil(o.Srid) {
		return nil, false
	}
	return o.Srid, true
}

// HasSrid returns a boolean if a field has been set.
func (o *GetReportDetailByPeriod200ResponseInner) HasSrid() bool {
	if o != nil && !isNil(o.Srid) {
		return true
	}

	return false
}

// SetSrid gets a reference to the given string and assigns it to the Srid field.
func (o *GetReportDetailByPeriod200ResponseInner) SetSrid(v string) {
	o.Srid = &v
}

func (o GetReportDetailByPeriod200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReportDetailByPeriod200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.DateFrom) {
		toSerialize["date_from"] = o.DateFrom
	}
	if !isNil(o.DateTo) {
		toSerialize["date_to"] = o.DateTo
	}
	if !isNil(o.CreateDt) {
		toSerialize["create_dt"] = o.CreateDt
	}
	if !isNil(o.SupRatingPrcUp) {
		toSerialize["sup_rating_prc_up"] = o.SupRatingPrcUp
	}
	if !isNil(o.IsKgvpV2) {
		toSerialize["is_kgvp_v2"] = o.IsKgvpV2
	}
	if !isNil(o.AcquiringFee) {
		toSerialize["acquiring_fee"] = o.AcquiringFee
	}
	if !isNil(o.AcquiringBank) {
		toSerialize["acquiring_bank"] = o.AcquiringBank
	}
	if !isNil(o.BonusTypeName) {
		toSerialize["bonus_type_name"] = o.BonusTypeName
	}
	if !isNil(o.Kiz) {
		toSerialize["kiz"] = o.Kiz
	}
	toSerialize["realizationreport_id"] = o.RealizationreportId
	if !isNil(o.SuppliercontractCode) {
		toSerialize["suppliercontract_code"] = o.SuppliercontractCode
	}
	toSerialize["rrd_id"] = o.RrdId
	toSerialize["gi_id"] = o.GiId
	toSerialize["subject_name"] = o.SubjectName
	if !isNil(o.NmId) {
		toSerialize["nm_id"] = o.NmId
	}
	toSerialize["brand_name"] = o.BrandName
	toSerialize["sa_name"] = o.SaName
	toSerialize["ts_name"] = o.TsName
	toSerialize["barcode"] = o.Barcode
	toSerialize["doc_type_name"] = o.DocTypeName
	toSerialize["quantity"] = o.Quantity
	toSerialize["retail_price"] = o.RetailPrice
	toSerialize["retail_amount"] = o.RetailAmount
	toSerialize["sale_percent"] = o.SalePercent
	toSerialize["commission_percent"] = o.CommissionPercent
	toSerialize["office_name"] = o.OfficeName
	toSerialize["supplier_oper_name"] = o.SupplierOperName
	if !isNil(o.OrderDt) {
		toSerialize["order_dt"] = o.OrderDt
	}
	if !isNil(o.SaleDt) {
		toSerialize["sale_dt"] = o.SaleDt
	}
	toSerialize["rr_dt"] = o.RrDt
	toSerialize["shk_id"] = o.ShkId
	if !isNil(o.RetailPriceWithdiscRub) {
		toSerialize["retail_price_withdisc_rub"] = o.RetailPriceWithdiscRub
	}
	if !isNil(o.DeliveryAmount) {
		toSerialize["delivery_amount"] = o.DeliveryAmount
	}
	if !isNil(o.ReturnAmount) {
		toSerialize["return_amount"] = o.ReturnAmount
	}
	if !isNil(o.DeliveryRub) {
		toSerialize["delivery_rub"] = o.DeliveryRub
	}
	toSerialize["gi_box_type_name"] = o.GiBoxTypeName
	if !isNil(o.ProductDiscountForReport) {
		toSerialize["product_discount_for_report"] = o.ProductDiscountForReport
	}
	if !isNil(o.SupplierPromo) {
		toSerialize["supplier_promo"] = o.SupplierPromo
	}
	if !isNil(o.Rid) {
		toSerialize["rid"] = o.Rid
	}
	toSerialize["ppvz_spp_prc"] = o.PpvzSppPrc
	toSerialize["ppvz_kvw_prc_base"] = o.PpvzKvwPrcBase
	toSerialize["ppvz_kvw_prc"] = o.PpvzKvwPrc
	toSerialize["ppvz_sales_commission"] = o.PpvzSalesCommission
	toSerialize["ppvz_for_pay"] = o.PpvzForPay
	toSerialize["ppvz_reward"] = o.PpvzReward
	toSerialize["ppvz_vw"] = o.PpvzVw
	toSerialize["ppvz_vw_nds"] = o.PpvzVwNds
	toSerialize["ppvz_office_id"] = o.PpvzOfficeId
	if !isNil(o.PpvzOfficeName) {
		toSerialize["ppvz_office_name"] = o.PpvzOfficeName
	}
	toSerialize["ppvz_supplier_id"] = o.PpvzSupplierId
	if !isNil(o.PpvzSupplierName) {
		toSerialize["ppvz_supplier_name"] = o.PpvzSupplierName
	}
	if !isNil(o.PpvzSupplierInn) {
		toSerialize["ppvz_supplier_inn"] = o.PpvzSupplierInn
	}
	if !isNil(o.DeclarationNumber) {
		toSerialize["declaration_number"] = o.DeclarationNumber
	}
	if !isNil(o.StickerId) {
		toSerialize["sticker_id"] = o.StickerId
	}
	if !isNil(o.SiteCountry) {
		toSerialize["site_country"] = o.SiteCountry
	}
	toSerialize["penalty"] = o.Penalty
	toSerialize["additional_payment"] = o.AdditionalPayment
	if !isNil(o.Srid) {
		toSerialize["srid"] = o.Srid
	}
	return toSerialize, nil
}

type NullableGetReportDetailByPeriod200ResponseInner struct {
	value *GetReportDetailByPeriod200ResponseInner
	isSet bool
}

func (v NullableGetReportDetailByPeriod200ResponseInner) Get() *GetReportDetailByPeriod200ResponseInner {
	return v.value
}

func (v *NullableGetReportDetailByPeriod200ResponseInner) Set(val *GetReportDetailByPeriod200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReportDetailByPeriod200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReportDetailByPeriod200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReportDetailByPeriod200ResponseInner(val *GetReportDetailByPeriod200ResponseInner) *NullableGetReportDetailByPeriod200ResponseInner {
	return &NullableGetReportDetailByPeriod200ResponseInner{value: val, isSet: true}
}

func (v NullableGetReportDetailByPeriod200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReportDetailByPeriod200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


